### ISSUE TITLE
Switch to jcenter from maven central to speed up build process

### ISSUE THREAD

**Issue by HappyRay** [azkaban/azkaban#1061]
see
I haven't tested it myself yet.

https://www.jfrog.com/knowledge-base/why-should-i-use-jcenter-over-maven-central/

http://kevinpelgrims.com/blog/2015/06/11/speeding-up-your-gradle-builds/

**Comment by suvodeep-pyne** [comment]
Don't know whether this is the best place for this conversation but should publish to jcenter aka bintray.com as well?

**Comment by HappyRay** [comment]
I don't see a clear difference in speed.
I will close this PR now until I see a clear evidence that jcenter is better.
see #1161 for details.
