### ISSUE TITLE
Remove usage of Hadoop private internal API FileSystem#getDelegationToken

### ISSUE THREAD

**Issue by xkrogen** [azkaban/azkaban#1066]
`HadoopSecurityManager_H_2_0` currently uses `FileSystem#getDelegationToken()` to retrieve delegation tokens for the default `FileSystem`. See the Javadoc of this method:

```java
  /**
   * Get a new delegation token for this file system.
   * This is an internal method that should have been declared protected
   * but wasn't historically.
   * Callers should use {@link #addDelegationTokens(String, Credentials)}
   * 
   * @param renewer the account name that is allowed to renew the token.
   * @return a new delegation token
   * @throws IOException
   */
  @InterfaceAudience.Private()
  public Token<?> getDelegationToken(String renewer) throws IOException {
```
The current usage will break if e.g. the default FS is `ViewFileSystem` and federation is being used, in which case `addDelegationTokens` will properly fetch all necessary DTs, but `getDelegationToken` will not.

**Comment by xkrogen** [comment]
The change for this is quite simple. I wanted to write a unit test but `HadoopSecurityManager_H_2_0` currently isn't really set up for that (e.g. being able to specify your own configuration, not using the execute-as-user binary); I would need to make some changes. Anyone have thoughts on whether I should just test manually or go ahead with changes to the security manager?

**Comment by wininco** [comment]
when i startup a azkaban use "./bin/azkaban-web-start.sh " , error:
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main"
who can help me,thinks , I am chinese

**Comment by xkrogen** [comment]
Hey @wininco, this isn't really the right place to ask about that. You may want to ask on the Google group: https://groups.google.com/forum/?fromgroups#!forum/azkaban-dev

**Comment by wininco** [comment]
OK thanks

**Comment by HappyRay** [comment]
@xkrogen The general expectation for new changes is to include automated tests. However I understand making the existing code easier to test is by itself a challenge. It may take more effort than the change itself. 

If the change is urgent, I am ok with a two step process: test manually first to get the change in, add automated tests later.

We can discuss what makes this code hard to test and what strategy we can use to refactor it to make it testable. Can you think of ways to test a small portion of the code you will touch? 

Please work with @suvodeep-pyne and @chengren311 who are working on executors.
