### ISSUE TITLE
scheduler - 2 or more azkaban-web-servers execute scheduled flow simultaneously

### ISSUE THREAD

**Issue by m4h** [azkaban/azkaban#1088]
Greetings,

We are evaluating AZK as scheduler for our data pipeline.
I've found misbehavior while running AZK in distributed  environment (2 web-servers, 1 exec-server, 1 separate DB):
- flow scheduled to run every minute (expected to see in flow executions 1 run per minute)
- however in flow executions I see 2 runs per minute.

If I leave only 1 AZK web-server working:
- flow executed and run only once per minute (as expected).

Please can someone clarify: 
- how scheduled flows are run (internally)
- how scheduler can be configured to guarantee run only once

**Comment by m4h** [comment]
In scrot below can be seen:
- executions 7011-7016 where run using 1 AZK web-server (1 per minute)
- executions 7019-7026 after starting another AZK web-server  (2 per minute)
![selection_004](https://cloud.githubusercontent.com/assets/970833/26033213/23f1422c-38b0-11e7-9458-2044a13a87bc.png)

This is scheduler definition.
![selection_005](https://cloud.githubusercontent.com/assets/970833/26033232/956b2cc4-38b0-11e7-84b5-7099c9974145.png)

**Comment by HappyRay** [comment]
Azkaban currently only supports one web server configuration.

**Comment by m4h** [comment]
The use case is simple - keep high availability of AZK web service (scheduler, user access).
