### ISSUE TITLE
azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'

### ISSUE THREAD

**Issue by boycode** [azkaban/azkaban#1124]
Tried all these options ( Execute-As-User in the main doc  - http://azkaban.github.io/azkaban/docs/latest/ ) Still getting the error .

azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib' .

Also from doc . It is not properly mentioned that for being a Execute-A-User , the plugin module are required mandatory or not inside azkaban-exec -snapshot/

Please any body can help on this . It is bit critical Struggling for 3 days.

Thanks,
Vishnu

**Comment by monkingmon** [comment]
Hi,I also meet this problem.I'm not sure whether to do so:
1,put execute-as-user.c into /home/azkaban/azkaban/azkaban-exec-server/plugins/jobtypes
2,gcc ${dirpath}/execute-as-user.c -o execute-as-user | chown root ${dirpath}/execute-as-user | chmod 6050 ${dirpath}/execute-as-user;dirpath=/home/azkaban/azkaban/azkaban-exec-server/plugins/jobtypes
3,modify ${dirpath}/commonprivate.properties --execute.as.user=true,azkaban.native.lib=/home/azkaban/azkaban/azkaban-exec-server/plugins/jobtypes
above,I can run some jobs which type are command.

**Comment by boycode** [comment]
I also tried the same steps you have mentioned but still this error is coming , tried all the possibilities.

- Since the comnplete stack trace of error is also not there . Struggling to fix this issue.

**Comment by boycode** [comment]
Hi ,

Fixed the issue .
Few things needs to be taken care .

1. with the above setting only in the executor will solve this problem
2. Better to give the absolute path for the executor-as-user 
3. Make sure that linux user and the user from the azkaban user manager  are the same
4. Keep only the commonprivate.prop in the jobtypes under exec. if you have any other plugin , need to setup it also clearly
5. while starting better to start as Sudo user for azkaban-web /exec.

Thanks,
Vishnu
