### ISSUE TITLE
TriggerRunnerManager-Trigger-Scanner-Thread  FAILD

### ISSUE THREAD

**Issue by maczpc** [azkaban/azkaban#119]
when i run bin/azkaban-web-start.sh

2014/01/28 13:57:48.357 +0800 INFO [Condition] [Azkaban] Testing condition BasicTimeChecker_1.eval()
2014/01/28 13:57:48.369 +0800 INFO [Condition] [Azkaban] Testing condition BasicTimeChecker_2.eval()
Exception in thread "TriggerRunnerManager-Trigger-Scanner-Thread" java.lang.IllegalMonitorStateException
    at java.lang.Object.wait(Native Method)
    at azkaban.trigger.TriggerManager$TriggerScannerThread.run(TriggerManager.java:242)
2014/01/28 13:57:48.696 +0800 INFO [log] [Azkaban] Started SslSocketConnector@0.0.0.0:8443
2014/01/28 13:57:48.696 +0800 INFO [AzkabanWebServer] [Azkaban] Server running on ssl port 8443.

So, schedule is invalid.

**Comment by davidzchen** [comment]
@maczpc I noticed that you referenced this issue from a PR in your fork. Do you think you can submit a PR to this repository if this issue is still reproducing?
