### ISSUE TITLE
2.1 hdfs browser plugin download (https://s3.amazonaws.com/azkaban2/azkaban-plugins/azkaban-hdfs-viewer-2.1.tar.gz) throwing 403's

### ISSUE THREAD

**Issue by puluanau** [azkaban/azkaban#14]
looks like a standard 403 from S3 to me...   Just an FYI, thanks for the work on the new site, looks awesome.

**Comment by itismewxg** [comment]
wonder if azkaban can provide the amazon s3 viewer plugin?
