### ISSUE TITLE
KILLING status job display exception in history view

### ISSUE THREAD

**Issue by zxhfounder** [azkaban/azkaban#1412]
When we have a KILLING status job, the history view can't display normally.
Our Azkaban version is 3.20.
![azkabanhistory](https://user-images.githubusercontent.com/22493638/29856812-ef7e94ae-8d87-11e7-8245-18ee8c1285fd.png)

**Comment by HappyRay** [comment]
It's strange. 
killing status is introduced in #1172 first included in 3.31 and later reverted in 3.32 #1300

**Comment by kunkun-tang** [comment]
@zxhfounder Is this your local setup or production server? What fix I did was trunk `execution_flow` table completly so no`killing` existing in DB.

**Comment by zxhfounder** [comment]
It's our test server. We have found the reason. Our executor used 3.31 version, different with the web server version 3.20.
Thanks a lot!
