### ISSUE TITLE
please expose the Executor_ID in /jmx

### ISSUE THREAD

**Issue by li-afaris** [azkaban/azkaban#1416]
When forcing a job flow on a particular executor, instead of running  a SQL to get the executor id, it would be nice to expose the Executor ID somewhere in the GUI.  The /jmx servlet inside the web server seems like it's a good location to display this info.   

Thanks

**Comment by hreview** [comment]
This is solved via Suvodeep’s
/status API

**Comment by li-afaris** [comment]
Oh right, yes it is.  Thanks for the reminder.
