### ISSUE TITLE
Remove code duplication in tests: createFlowRunner

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#1433]
Raised by @HappyRay: https://github.com/azkaban/azkaban/pull/1244#issuecomment-326722462

All of these tests have methods by that name, which overlap more or less:
```
FlowRunnerPipelineTest.java
FlowRunnerPropertyResolutionTest.java
FlowRunnerTest.java
FlowRunnerTest2.java
LocalFlowWatcherTest.java
RemoteFlowWatcherTest.java
```

Combine them as much as possible and move to `FlowRunnerTestUtil`.

Let's have this merged first to avoid conflicts: https://github.com/azkaban/azkaban/pull/1432

**Comment by juhoautio** [comment]
Also the FlowRunnerPipelineTest has some `createFlowRunner` methods, so let's also have this first: https://github.com/azkaban/azkaban/pull/1243

**Comment by juhoautio** [comment]
@ameyamk please let me know if there's review resources available for this change. Otherwise we could close the issue.

**Comment by ameyamk** [comment]
I am sorry Juho. We are slammed right now.

**Comment by HappyRay** [comment]
@juhoautio if you submit a PR for this issue, I will review it. Thanks
