### ISSUE TITLE
Rename ajax action loadFlow to fetchSchedules and document it

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#1506]
On the ScheduleServlet there's an ajax action [loadFlow](https://github.com/azkaban/azkaban/blob/master/azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java#L93-L94) that returns a list of all schedules. [It doesn't take any parameters](https://github.com/azkaban/azkaban/blob/master/azkaban-web-server/src/main/java/azkaban/webapp/servlet/ScheduleServlet.java#L108-L132).

The name is really misleading. I suggest renaming it to `fetchSchedules` (we can also keep the old `loadFlow` for backward compatibility).

Then it would be good to document it in http://azkaban.github.io/azkaban/docs/latest/#ajax-api as new sub-section `Fetch all schedules`.

**Comment by kunkun-tang** [comment]
Sounds good! How about `fetchAllSchedules` ?

**Comment by HappyRay** [comment]
If it is not documented, it is considered internal, probably to support the UI.

I would suggest updating the name and callers. I suspect it is called by some js files. 

We would like to improve our API in the near future. I hesitate to expand our public API set now.

**Comment by juhoautio** [comment]
> How about fetchAllSchedules ?

I thought that `fetchSchedules` would be nicer because you can assume that without any additional params it returns everything. And then there's room for expansion: it would be easy to add support for some filter parameters like project id, and the name `fetchSchedules` would still work well.

**Comment by juhoautio** [comment]
> I would suggest updating the name and callers

I'd like that. Want me to make a PR?

**Comment by wyukawa** [comment]
I use loadFlow API to get all schedules, but actually I think that the name is misleading...

**Comment by kunkun-tang** [comment]
@juhoautio Sounds good. Filter can be an option.

**Comment by HappyRay** [comment]
I'd welcome a PR.

**Comment by juhoautio** [comment]
It's been renamed to `fetchSchedules` but `loadFlow` is still kept as an alias for compatibility.
