### ISSUE TITLE
Graph visualisation breaks in some rare cases

### ISSUE THREAD

**Issue by armisael** [azkaban/azkaban#1508]
## How to reproduce
1) Create a project starting from this [_project.zip](https://github.com/azkaban/azkaban/files/1337700/_project.zip) (it's one of our production flows, I had to obfuscate job names, sorry for that);
1) Open the job named `wwww-wwwww-wwwww`
1) Expand the nested flow `ccccc-cc-ccccc-ccccccc`

This appears:
![screenshot 2017-09-27 17 05 08](https://user-images.githubusercontent.com/71387/30921141-08d3d84a-a3a6-11e7-88ea-8ca0b57a9210.png).

I have a fix ready for this, I will push it soon.

**Comment by HappyRay** [comment]
Thanks.
