### ISSUE TITLE
Error: Could not find or load main class 12321

### ISSUE THREAD

**Issue by lijixiang123** [azkaban/azkaban#1512]
i alradly configure the properties file,and run the bin/azkaban-executor-start.sh
then the issue as follow
"Error: Could not find or load main class 12321"
i wish somebody can help me to solve the issue,ths.

**Comment by PoorvaLunawat** [comment]
Any updates on this? I am facing the same issue while using Azkaban Multiple Executor Mode on Windows 10. 

Any help will be really appreciated.
