### ISSUE TITLE
No active executor found

### ISSUE THREAD

**Issue by lijixiang123** [azkaban/azkaban#1513]
after configur the properties file,i run the bin/azkaban-web-start.sh
then the issue as follow:
 Error injecting constructor, azkaban.executor.ExecutorManagerException: No active executor found
  at azkaban.executor.ExecutorManager.<init>(ExecutorManager.java:132)
  at azkaban.executor.ExecutorManager.class(ExecutorManager.java:73)
  while locating azkaban.executor.ExecutorManager
    for the 3rd parameter of azkaban.trigger.TriggerManager.<init>(TriggerManager.java:58)
  at azkaban.trigger.TriggerManager.class(TriggerManager.java:39)
  while locating azkaban.trigger.TriggerManager
    for the 5th parameter of azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:155)
  at azkaban.webapp.AzkabanWebServerModule.configure(AzkabanWebServerModule.java:52)
  while locating azkaban.webapp.AzkabanWebServer
Caused by: azkaban.executor.ExecutorManagerException: No active executor found
        at azkaban.executor.ExecutorManager.setupExecutors(ExecutorManager.java:226)
        at azkaban.executor.ExecutorManager.<init>(ExecutorManager.java:137)
        at azkaban.executor.ExecutorManager$$FastClassByGuice$$e1c1dfed.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFa

**Comment by HappyRay** [comment]
Please follow the setup guide to set up and activate executors.

**Comment by tschutte** [comment]
"Please follow the setup guide to set up and activate executors."

It would be helpful if the documentation highlighted this dependency ordering between the executor and web servers.

**Comment by FourSpaces** [comment]
Follow the setup guide to set up and activate the executive.
In the case of activation of the program execution, there may be a problem with the database, and the data in the 'executors' table in the database needs to be modified.
E.g
----------------------------------------------
id    host                port         active
1	localhost	12321	1
5	office-prod-bigdata-00	12321	0
----------------------------------------------

You need to change the corresponding actuator's active to 1, you can run, execute the program. It seems that there are some bugs, you can't modify the database information in time.

================中文=====================
请按照设置指南设置和激活执行程序。
在激活程序执行的情况下，有可能是数据库的问题，需要修改 数据库中 'executors' 表中 的数据
例如
id    host                port         active
1	localhost	12321	1
5	office-prod-bigdata-00	12321	0

你需要将 对应执行器的 active 改为1， 就可以运行，执行程序 好像有些BUG，不能及时修改数据库的信息

**Comment by FourSpaces** [comment]
Follow the setup guide to set up and activate the executive.
In the case of activation of the program execution, there may be a problem with the database, and the data in the 'executors' table in the database needs to be modified.
E.g
----------------------------------------------
id    host                port         active
1	localhost	12321	1
5	office-prod-bigdata-00	12321	0
----------------------------------------------

You need to change the corresponding actuator's active to 1, you can run, execute the program. It seems that there are some bugs, you can't modify the database information in time.

================中文=====================
请按照设置指南设置和激活执行程序。
在激活程序执行的情况下，有可能是数据库的问题，需要修改 数据库中 'executors' 表中 的数据
例如
id    host                port         active
1	localhost	12321	1
5	office-prod-bigdata-00	12321	0

你需要将 对应执行器的 active 改为1， 就可以运行，执行程序 好像有些BUG，不能及时修改数据库的信息

**Comment by zhangqingkai** [comment]
I have the seem question，when I run the ./bin/start-web.sh, it will report No active executor found, and I see the executors table, it is empty, I can't even modify the active status manually, anyone can help me?

**Comment by jaihind213** [comment]
@zhangqingkai  i had the same issue.  
how to fix:
1)start executor and on that host do curl
2)curl -G "http://localhost:<executor_port>/executor?action=activate" && echo

this is mentioned here 
https://azkaban.readthedocs.io/en/latest/getStarted.html#getting-started-with-the-multi-executor-server

**Comment by leqii-com** [comment]
@FourSpaces ThankS，very good。加个| 1 | 127.0.0.1| 12321 | 1   就可以了。
