### ISSUE TITLE
Trouble in creating flow

### ISSUE THREAD

**Issue by YapingWu** [azkaban/azkaban#1535]
There are three jobs, the dependency is, B depends on A, C depends on A, Figure 1 is the job configuration information,  azkaban generated the flow shown in Figure 2, but I want to generate the flow as shown in Figure 3 , what should i do?
![figure1](https://user-images.githubusercontent.com/16968238/31534159-4facbcb2-b028-11e7-8fc4-de3775402856.png)
![figure2](https://user-images.githubusercontent.com/16968238/31534182-7269b69c-b028-11e7-8e2f-bfb1ba62dd7e.png)
![figure3](https://user-images.githubusercontent.com/16968238/31534185-756d844a-b028-11e7-80a9-d1c252fc640a.png)

**Comment by ismailsimsek** [comment]
Hi 

i believe you need another job which ties them together, try to a dd anew job like below.

```
#Job_NameofMyflow.job
type=command
command=echo 'end'
dependencies=JobB,JobC
```

**Comment by YapingWu** [comment]
ok,I get it,thank you very much.

**Comment by HappyRay** [comment]
Thanks @ismailsimsek

**Comment by wu8685** [comment]
I encountered this problem on Azkaban 3.0.
Will it be fixed ?
