### ISSUE TITLE
azkaban web cannot load any js or css

### ISSUE THREAD

**Issue by diaowenyang** [azkaban/azkaban#1561]
HI:
  I just deploy azkaban-web-server-3.35.0-16. When I azkaban-web-start.sh,it doesnot get any errors.
  When I login it on firefox/chrome ,There are no styles in the page.
![1](https://user-images.githubusercontent.com/18416111/32816955-467dc234-c9f6-11e7-9c23-f6d4238e46d4.png)
![2](https://user-images.githubusercontent.com/18416111/32816956-46b16d00-c9f6-11e7-80aa-18e1f22390f8.png)

Would you give me any suggessions?

**Comment by kunkun-tang** [comment]
No that familiar with azkaban-web-start.sh, but have you define where the web resource is before you start the web server?

You need to define the web resource location by
```
web.resource.dir=azkaban-web-server/build/install/azkaban-web-server/web
```
in azkaban.properties

**Comment by diaowenyang** [comment]
It works,Thank you so much!
