### ISSUE TITLE
Azkaban 3.37.0 SLA options cannot remove

### ISSUE THREAD

**Issue by dinusha00** [azkaban/azkaban#1576]
I am using Azkaban 3.37.0 (two server mode) SLA options cannot remove after we created. It always says "SLA for schedule must have at least one action". The older versions allowed to remove this but not with this new version

**Comment by chengren311** [comment]
hey, thanks for reporting this issue. I'm not able to reproduce this issue. Can you post the screen shot of your schedule/sla setup and the error message.

**Comment by dinusha00** [comment]
Hi, Thanks for the reply. Below is the screenshot when a user tries to remove the already existing SLA by removing the details. Or we have another way to remove the set SLA? Cannot find any other way to do this and in older versions when i remove all the values and save, similar to what i am doing now, then the SLA will get removed. But not in this version. Can you confirm if its not reproducible, then i have to recompile another latest version from the beginning and try these options.

![screen shot 2017-12-07 at 10 00 49 am](https://user-images.githubusercontent.com/7746532/33694923-b4271e66-db35-11e7-91ec-070846e88c95.png)

**Comment by chengren311** [comment]
hi, you cannot remove SLA from this page. SLA can only be removed by removing the associated schedule. See https://github.com/azkaban/azkaban/issues/1347
