### ISSUE TITLE
Azkaban 3.37.0 SLA options => Flow SLA Rules email action issue

### ISSUE THREAD

**Issue by dinusha00** [azkaban/azkaban#1577]
I am using Azkaban 3.37.0 (two server mode) SLA options => Flow SLA Rules => Email Action

When setting a "Duration" by selecting only "Email Action" will not receive any email alert when a job/flow takes more that the given time. Anyway if we select both "Email Action" and "Kill Action", then it will kill the job and will send an email correctly. 

So due to this bug, if we don't want to kill the long running process, but receive an email when a job takes longer time, will not work.

This works well with older versions but not with this new version

Below is the 'working' settings screenshot
![email working](https://user-images.githubusercontent.com/7746532/33695238-29b8a7c0-db37-11e7-9d95-40d20efaaeda.png)

Below is the 'not working' settings screenshot
![email not working](https://user-images.githubusercontent.com/7746532/33695253-41a8a222-db37-11e7-8641-a9017468e8e6.png)

Thanks!

**Comment by chengren311** [comment]
hey, not able to get a reproduce either. Did you observe anything outstanding in the log?(e.x email sending failure)

**Comment by dinusha00** [comment]
Hi, I will try with newer version and will post if i was able to find anything from logs. thanks for the message. Closing the ticket, since its not reproducible for others

**Comment by yangxu1362850636** [comment]
hi, i used azkaban sla to alert my job, but it did not works,only killed the job which timeout, but did not send any emails to me, my azkaban's version is 3.30.1 @chengren311

**Comment by chengren311** [comment]
@yangxu1362850636 3.30.1 is pretty old. Please consider upgrading to latest. Also what's your email setting, did you configure your email setting correctly in your azkaban.properties file? Can the email address receive flow failure/success email? Did you observe anything outstanding in the log when job killing by SLA happens?

**Comment by yangxu1362850636** [comment]
@chengren311  thanksfor your reply, I'm sure my configuration of azkaban emails is correct,and , i can receive failure/success email from my azkaban, but , i can't receive any sla emails from sla,and The sla timeout  kill has no effect on the spark task submitted to yarn. I am very confused

**Comment by chengren311** [comment]
@yangxu1362850636 can you try latest version?

**Comment by yangxu1362850636** [comment]
i did not, this is about versions???
