### ISSUE TITLE
azkaban 3.28.0 hadoopJavaJob at hdp with kerberos  run failed

### ISSUE THREAD

**Issue by llbb2000go** [azkaban/azkaban#1585]
hdp.version=2.5.3.0-37
In commonprivate.properties I have set:
---------------------------------------------------
obtain.binary.token=true
obtain.namenode.token=true
obtain.jobtracker.token=true
obtain.jobhistoryserver.token=true
-------------------------------------------------------
The error log:
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - Search Subject for SPNEGO INIT cred (<<DEF>>, sun.security.jgss.spnego.SpNegoCredElement)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - Search Subject for Kerberos V5 INIT cred (<<DEF>>, sun.security.jgss.krb5.Krb5InitCredential)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - >>>KinitOptions cache name is /tmp/krb5cc__hadoopJava_job_2__hadoopJava-wordcount__hadoopJava-wordcount__190__hdfs
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - Negotiate support not initiated, will fallback to other scheme if allowed. Reason:
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null)))
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.spnego.SpNegoContext.initSecContext(SpNegoContext.java:454)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:248)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.spnego.NegotiatorImpl.init(NegotiatorImpl.java:108)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.spnego.NegotiatorImpl.<init>(NegotiatorImpl.java:117)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.Negotiator.getNegotiator(Negotiator.java:63)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.NegotiateAuthentication.isSupportedImpl(NegotiateAuthentication.java:130)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.NegotiateAuthentication.isSupported(NegotiateAuthentication.java:102)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.AuthenticationHeader.parse(AuthenticationHeader.java:200)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.AuthenticationHeader.<init>(AuthenticationHeader.java:143)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.AuthenticationHeader.<init>(AuthenticationHeader.java:123)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1696)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.authentication.client.KerberosAuthenticator.authenticate(KerberosAuthenticator.java:191)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticator.authenticate(DelegationTokenAuthenticator.java:132)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.authentication.client.AuthenticatedURL.openConnection(AuthenticatedURL.java:216)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticator.doDelegationTokenOperation(DelegationTokenAuthenticator.java:298)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticator.getDelegationToken(DelegationTokenAuthenticator.java:170)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticatedURL.getDelegationToken(DelegationTokenAuthenticatedURL.java:371)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl$1.run(TimelineClientImpl.java:368)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl$1.run(TimelineClientImpl.java:360)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.security.AccessController.doPrivileged(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1724)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl$TimelineClientRetryOpForOperateDelegationToken.run(TimelineClientImpl.java:699)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl$TimelineClientConnectionRetry.retryOn(TimelineClientImpl.java:185)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.operateDelegationToken(TimelineClientImpl.java:462)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.getDelegationToken(TimelineClientImpl.java:372)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getTimelineDelegationToken(YarnClientImpl.java:354)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.addTimelineDelegationToken(YarnClientImpl.java:335)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:255)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapred.ResourceMgrDelegate.submitApplication(ResourceMgrDelegate.java:291)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:290)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:240)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.security.AccessController.doPrivileged(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1724)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:575)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:570)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.security.AccessController.doPrivileged(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1724)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:570)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:561)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.javautils.AbstractHadoopJob.run(AbstractHadoopJob.java:107)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at com.ys.azkaban.job.hadoopjava.main.HadoopJavaJobMain.customRun(HadoopJavaJobMain.java:96)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.runMethod(HadoopJavaJobRunnerMain.java:244)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.access$000(HadoopJavaJobRunnerMain.java:40)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain$2.run(HadoopJavaJobRunnerMain.java:235)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain$2.run(HadoopJavaJobRunnerMain.java:225)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.security.AccessController.doPrivileged(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1724)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.runMethodAsUser(HadoopJavaJobRunnerMain.java:225)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.<init>(HadoopJavaJobRunnerMain.java:178)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.main(HadoopJavaJobRunnerMain.java:69)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - Caused by: GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:343)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:145)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.spnego.SpNegoContext.GSS_initSecContext(SpNegoContext.java:882)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.spnego.SpNegoContext.initSecContext(SpNegoContext.java:317)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	... 67 more
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - Caused by: javax.security.auth.login.LoginException: No password provided
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:919)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.security.AccessController.doPrivileged(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.GSSUtil.login(GSSUtil.java:258)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5Util.getTicket(Krb5Util.java:158)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:335)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:331)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at java.security.AccessController.doPrivileged(Native Method)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:330)
15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - 	... 75 more

**Comment by kunkun-tang** [comment]
The failure could be many causes. Do you use execute.as.user feature?

Have you tried running Kerberos manually on your host?

**Comment by llbb2000go** [comment]
After checking error log, it turned out that the problem was that   yarn timeline service is enabled.
`15-12-2017 18:11:36 CST hadoopJava-wordcount INFO - at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.operateDelegationToken(TimelineClientImpl.java:462)`
One approach to this issue is to set yarn.timeline-service.enabled=false, it is simple and effective in development environments.
Another is modify prefetchToken method, add timeline service token when yarn.timeline-service.enabled=true

 if (conf.getBoolean(YARN_TIMELINE_ENABLE, false)) {
      logger.info("Yarn Config " + YARN_TIMELINE_ENABLE + " : " + "true");
      try {

        TimelineClient timelineClient = TimelineClient.createTimelineClient();
        String rmPrincipal = conf.get(YarnConfiguration.RM_PRINCIPAL);
        String renewer = null;
        if (rmPrincipal != null && rmPrincipal.length() > 0) {
          String rmHost = conf.getSocketAddr(
              YarnConfiguration.RM_ADDRESS,
              YarnConfiguration.DEFAULT_RM_ADDRESS,
              YarnConfiguration.DEFAULT_RM_PORT).getHostName();
          renewer = SecurityUtil.getServerPrincipal(rmPrincipal, rmHost);
        }

        timelineClient.init(conf);
        Token<TimelineDelegationTokenIdentifier> timelineToken = timelineClient
            .getDelegationToken(renewer);
        if (timelineToken == null) {
          logger.error("Failed to fetch TimeLine token");
        }
        logger.info("Created TimeLine token.");
        logger.info("Token kind: " + timelineToken.getKind());
        logger.info("Token service: " + timelineToken.getService());
        cred.addToken(timelineToken.getService(), timelineToken);
      } catch (IOException e) {
        final String message =
            "Failed to get timeline server token." + e.getMessage()
                + e.getCause();
        logger.error(message, e);
        throw new HadoopSecurityManagerException(message);
      } catch (YarnException y) {
        final String message =
            "Failed to get timeline server token." + y.getMessage()
                + y.getCause();
        logger.error(message, y);
        throw new HadoopSecurityManagerException(message);
      }
    }
