### ISSUE TITLE
Questions about contributing to the project

### ISSUE THREAD

**Issue by haknsahn** [azkaban/azkaban#1595]
Hi,

I am a software engineer at Global Maksimum, we are using Azkaban to manage our daily jobs which are mostly related to **Hadoop** and **Vertica**. These are using basically **hadoopJava** and **command** job types with **Spark**, **Sqoop** commands and also direct Vertica queries. These Vertica queries are prepared by another job type implemented by our team.

The reason behind opening this issue is that we are interested in actively contributing to the **azkaban** and also the **azkaban-plugins** repo. However before starting to contribution, we have some questions about the project.

- Do you continue to maintain the **[azkaban-plugins](https://github.com/azkaban/azkaban-plugins)** repo ? Should we prefer to contribute to this repo in case of writing a new plugin ? I think if the implementation will be related to an existing plugin, it would be better contributing to the azkaban-plugins repo (i.e. the job type we are currently using to execute Vertica queries). However what if it is a different plugin ? I am asking this because Hadoop Security plugin has been moved to this repo from the azkaban-plugins, which is motivated by the azkaban-plugins' not maintaining well.

- We want to test **Flow 2.0** design by converting our existing projects to Flow 2.0 design (in a test environment 😇) but I could not find any documentation or a feature list of it. Should we look for related commits and read the code or do you have any documentation to share with us ? (and also information about progress of the design.)

We will really appreciate any information/help you can provide.
Thank you.

**Comment by HappyRay** [comment]
Thanks for your interest and reaching out!

Yes, we still maintain the plugins repo. However, we plan to merge that repo with this one in the near future. For new job type plugins, I'd suggest contributing directly to the main repo. 

@jamiesjc plans to share more details on Flow 2.0 design soon.

In case you haven't, please take a look at the contribution guide at
https://github.com/azkaban/azkaban/blob/master/CONTRIBUTING.md

**Comment by jamiesjc** [comment]
Hi @haknsahn, we're glad to know that you are interested in our new Flow 2.0 design!
I've just written a wiki with some details on Flow 2.0 design. Let me know if you need more clarification. We are mostly done with the code. Welcome to test it and report any bug! :) 
User guide: 
https://github.com/azkaban/azkaban/wiki/Azkaban-Flow-2.0-Design---User-Guide
PRs:
https://github.com/azkaban/azkaban/issues/1453
