### ISSUE TITLE
Sorry, I got one question .

### ISSUE THREAD

**Issue by huaxuechensu** [azkaban/azkaban#1607]
I can't figure out how version number  generated  when I execute  './gradlew build -x test' .  
then I get "azkaban-web-server-3.41.0-1-g8cec3999.jar"    
the "3.41.0-1-g8cec3999"  make confused.
Could someone tell me  how it works . 

thanks a lot .

**Comment by HappyRay** [comment]
> Please don't report an issue as a way to ask a question. Use the Google group instead.
Please take a look at https://github.com/azkaban/azkaban/blob/master/CONTRIBUTING.md
Your question is better answered there.

**Comment by huaxuechensu** [comment]
Thanks a lot man, I got that.
