### ISSUE TITLE
Issue with downloading zip from project

### ISSUE THREAD

**Issue by ggalves** [azkaban/azkaban#1618]
Any logged user can download zip from projects with a request to `/manager?project=${project.name}&download=true`, even if they don't have any permission to the project

**Comment by HappyRay** [comment]
Thanks for reporting this issue!
Someone will follow up. 
Are you interested in contributing a fix?

**Comment by ggalves** [comment]
Sorry for the late to respond. I created a PR to fix it, can you review?

Thanks!

**Comment by HappyRay** [comment]
@ggalves 
Thanks!

@reallocf  you are secondary on call this week. Could you take a look?
