### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.derby.jdbc.AutoloadedDriver40

### ISSUE THREAD

**Issue by haiyes** [azkaban/azkaban#1636]
when i started the azkaban web, this was happened.
2018/02/08 14:56:50.455 ERROR Exception in thread "main" 
2018/02/08 14:56:50.456 ERROR java.lang.NoClassDefFoundError: Could not initialize class org.apache.derby.jdbc.AutoloadedDriver40
2018/02/08 14:56:50.457 ERROR 	at java.lang.Class.forName0(Native Method)
2018/02/08 14:56:50.458 ERROR 	at java.lang.Class.forName(Class.java:348)
2018/02/08 14:56:50.458 ERROR 	at java.sql.DriverManager.isDriverAllowed(DriverManager.java:556)
2018/02/08 14:56:50.458 ERROR 	at java.sql.DriverManager.isDriverAllowed(DriverManager.java:548)
2018/02/08 14:56:50.458 ERROR 	at java.sql.DriverManager.getDrivers(DriverManager.java:446)
2018/02/08 14:56:50.459 ERROR 	at org.apache.commons.dbcp2.BasicDataSource.<clinit>(BasicDataSource.java:77)
2018/02/08 14:56:50.459 ERROR 	at azkaban.db.MySQLDataSource$$FastClassByGuice$$9a694745.newInstance(<generated>)

Can anyone help me?

**Comment by arcticOak2** [comment]
@haiyes can you please share the solution for this issue.

**Comment by yinmazhong** [comment]
为什么已经关闭了，怎么解决的？

**Comment by yinmazhong** [comment]
字面意思
找个derby.jar放到lib目录下即可
有人说在jdk下有，找，发现jdk1.8竟然没有，而jdk1.7有找个文件
