### ISSUE TITLE
QuartzScheduler is enabled even its set to false 

### ISSUE THREAD

**Issue by ismailsimsek** [azkaban/azkaban#1641]
with azkaban soloserver 3.42.0  i see Quartz scheduler when i want to schedule a flow where i was expecting old scheduler UI and settings.

i added following line to conf/azkaban.properties file 
`azkaban.server.schedule.enable_quartz=false`

**Comment by chengren311** [comment]
@ismailsimsek thanks for reporting the issue!
- i see Quartz scheduler when i want to schedule a flow
what did you see exactly.

Also the default value for the flag is false so you don't have to specify it if  you wanna disable quartz.

@kunkun-tang should we document that quartz is still in development mode?

**Comment by kunkun-tang** [comment]
The AZ quartz module is developed. The UI you see is using a separate Scheduler module, which doesn't use core Quartz scheduler. We haven't figured out the solution to migrate the today's schedule to quartz.

**Comment by ismailsimsek** [comment]
im seing following UI . is it default scheduler UI now? 
![quartz](https://user-images.githubusercontent.com/6005685/36246356-bb7e68be-122f-11e8-855b-917662f91dcd.png)

where i was expecting old scheduler UI
![fireshot capture 038 - azkaban web client - https___bietl ui techops eu_manager_project reports](https://user-images.githubusercontent.com/6005685/36246363-c5cc6e74-122f-11e8-8c85-ded39ec09ab6.png)
