### ISSUE TITLE
NPE thrown while shutting down

### ISSUE THREAD

**Issue by senecaso-sf** [azkaban/azkaban#1681]
Using build 3.43.0, I noticed that when I kill the web node, an NPE is logged while attempting to shutdown the Quartz scheduler, even though the Quartz scheduler has been disabled.

```
2018/03/08 00:04:49.599 +0000 INFO [AzkabanWebServer] [Azkaban] Shutting down flow trigger scheduler...
2018/03/08 00:04:49.599 +0000 INFO [QuartzScheduler] [Azkaban] Shutting down scheduler
2018/03/08 00:04:49.600 +0000 ERROR [StdOutErrRedirect] [Azkaban] Exception in thread "Thread-8" 
2018/03/08 00:04:49.600 +0000 ERROR [StdOutErrRedirect] [Azkaban] java.lang.NullPointerException
2018/03/08 00:04:49.600 +0000 ERROR [StdOutErrRedirect] [Azkaban]       at azkaban.scheduler.QuartzScheduler.shutdown(QuartzScheduler.java:108)
2018/03/08 00:04:49.601 +0000 ERROR [StdOutErrRedirect] [Azkaban]       at azkaban.flowtrigger.quartz.FlowTriggerScheduler.shutdown(FlowTriggerScheduler.java:174)
2018/03/08 00:04:49.601 +0000 ERROR [StdOutErrRedirect] [Azkaban]       at azkaban.webapp.AzkabanWebServer$1.run(AzkabanWebServer.java:240)
```

I believe this is happening because the QuartzScheduler class is leaving the `scheduler` variable as `null` if the scheduler is disabled, but during shutdown the `shutdown()` method is called and its not checking `scheduler` [for null first](https://github.com/azkaban/azkaban/blob/master/azkaban-web-server/src/main/java/azkaban/scheduler/QuartzScheduler.java#L108).

**Comment by chengren311** [comment]
@senecaso-sf  thanks for reporting this issue. The fix(https://github.com/azkaban/azkaban/pull/1684) was put in and we will do a release soon. BTW quartz feature is still under development so we don't expect this to be used in production.

**Comment by senecaso-sf** [comment]
Perfect, thanks!
