### ISSUE TITLE
Log layout pattern as a property

### ISSUE THREAD

**Issue by gerashegalov** [azkaban/azkaban#1718]
`JobRunner` currently hardcodes the layout
`%d{dd-MM-yyyy HH:mm:ss z} %c{1} %p - %m\n`. However users might want a different timezone or other customizations

**Comment by HappyRay** [comment]
I agree.

It's on the todo list to give user jobs more control over logging.

**Comment by chengren311** [comment]
thanks for the contribution!

**Comment by HappyRay** [comment]
Thanks.

This PR helps.

What I proposed to the team was to find an alternative design so that AZ interfere with job code's logging as little as possible. i.e. normal logging for jobs should be the job designers' chose and responsibility. I believe this design is possible. Make sense?

**Comment by gerashegalov** [comment]
Yes, absolutely.  It's actually one of the problems I was thinking of solving. Once the JobRunner started consuming the child process output it should stop applying its own conversion pattern on top of it. Otherwise multiline logging statements such as stack traces and pretty-printed jsons from the child process appear to be broken single-line statements and confuse log parsers of log  analyzers.
