### ISSUE TITLE
Level of a Node in a flow is always 0

### ISSUE THREAD

**Issue by sjakthol** [azkaban/azkaban#1793]
224d278ddb7bacf482ff2264e807ff186e2302eb refactored the way a level of a node is calculated. The new code contains a minor bug that causes the level to be 0 for all nodes. This breaks the job list dropdown on the project page as the jobs are not ordered / indented properly (level is used for order and indentation).

The bug is at https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/flow/Flow.java#L198 where the code calls `setLevelsAndEdgeNodes(nextLevelNodes, level++);` to set levels for the next level of nodes. However, the way postfix operators work in Java is that the value of the variable is first used and only then incremented. This means the current value of level is passed to the recursive setLevelsAndEdgeNodes call instead of the incremented value.

That line should be modified to either do `++level` which first increments the value and then returns it or `level + 1` which achieves the same result.

**Comment by HappyRay** [comment]
Thanks.

This is related to #1680

**Comment by sjakthol** [comment]
Fix here: https://github.com/azkaban/azkaban/pull/1794
