### ISSUE TITLE
when  a job is killed in UI,it's still running on server

### ISSUE THREAD

**Issue by YapingWu** [azkaban/azkaban#1836]
My azkaban version is 3.20.0. I have used Command Job Type in azkaban.
When I kill a flow,and it's status is killed in UI. But usually I found the command which is configured in the job is still running on server.

**Comment by afsaar** [comment]
@YapingWu  did you the get the solution. i am also facing same issue

**Comment by YapingWu** [comment]
In my case,when the job is running, a process is created, and the process creates multiple child processes.
If I kill the job, azkaban will only kill the parent process, and the child process will not be killed at the same time.So I modified the source code of azkaban, I will get all of its child processes before killing the parent process, and then kill those child processes after killing the parent process.

**Comment by lhsniper** [comment]
> In my case,when the job is running, a process is created, and the process creates multiple child processes.
> If I kill the job, azkaban will only kill the parent process, and the child process will not be killed at the same time.So I modified the source code of azkaban, I will get all of its child processes before killing the parent process, and then kill those child processes after killing the parent process.
Facing the same issue,Can you share the experience how to solve this problem in detail?

**Comment by YapingWu** [comment]
@lhsniper I had modified the function `cancel()`  of `/azkaban-common/src/main/java/azkaban/jobExecutor/ProcessJob.java`,and killed the child process which was not killed after its parent process killed.
