### ISSUE TITLE
create db error~

### ISSUE THREAD

**Issue by happyapple668** [azkaban/azkaban#1934]
https://github.com/happyapple668/pics/blob/master/issue/azkaban/create_db_error.jpg
I change the length of the column and then succeed~

**Comment by juhoautio** [comment]
@happyapple668 See this: https://github.com/azkaban/azkaban/pull/1694#issuecomment-398513531

Different MySQL versions have different defaults. Simple way to increase the index key prefix length is to upgrade to MySQL 5.7, if possible. It may be possible to also change the limit by configuration without changing MySQL version.
