### ISSUE TITLE
no GUI for modify project/flow?

### ISSUE THREAD

**Issue by Lqlsoftware** [azkaban/azkaban#1936]
Why there is no GUI for modify project/flow?
It is such a disaster when i got hundreds of job. Can there be a mind-mapper-like online editor? It can save a lot of my time.

**Comment by kunkun-tang** [comment]
At linkedin, we use Hadoop DSL to contruct workflows.

https://github.com/linkedin/linkedin-gradle-plugin-for-apache-hadoop/wiki/Hadoop-DSL-Language-Reference

**Comment by Lqlsoftware** [comment]
@kunkun-tang Thx, bro
But sometimes we don't want to edit any code or something to modify my company's workflows.
Lazy aha. Your solution is very elegant, but a non-coder cannot figure it out in a shortly time.
