### ISSUE TITLE
azkaban Failure Options   Finish All Possible

### ISSUE THREAD

**Issue by zengqingjun** [azkaban/azkaban#1966]
I set Finish All Possible, but the current job failed, the latter one will not be executed?

I now have a C.job that relies on A.job and B.job. No matter which one fails in AB, I will execute C.job. How do I configure it?

**Comment by zengqingjun** [comment]
Setting Finish All Possible still does not take effect

**Comment by gaoying0805** [comment]
i get it too

**Comment by gaoying0805** [comment]
没有搞定的话  看看这个帖子https://github.com/azkaban/azkaban/issues/1451
