### ISSUE TITLE
azkaban compile failed

### ISSUE THREAD

**Issue by modeyang** [azkaban/azkaban#1999]
compile it with **jdk1.8.0_181**,  error message below
```
-> # ./gradlew build installDist
Parallel execution with configuration on demand is an incubating feature.

> Task :azkaban-exec-server:compileTestJava 
/data/git_workspace/azkaban/azkaban-exec-server/src/test/java/azkaban/dag/DagServiceTest.java:32: error: package javafx.util does not exist
import javafx.util.Pair;
                  ^
/data/git_workspace/azkaban/azkaban-exec-server/src/test/java/azkaban/dag/StatusChangeRecorder.java:24: error: package javafx.util does not exist
import javafx.util.Pair;
                  ^
/data/git_workspace/azkaban/azkaban-exec-server/src/test/java/azkaban/dag/DagServiceTest.java:56: error: cannot find symbol
  private final List<Pair<String, Status>> expectedSequence = new ArrayList<>();
                     ^
  symbol:   class Pair
  location: class DagServiceTest
/data/git_workspace/azkaban/azkaban-exec-server/src/test/java/azkaban/dag/StatusChangeRecorder.java:31: error: cannot find symbol
  private final List<Pair<String, Status>> sequence = new ArrayList<>();
                     ^
  symbol:   class Pair
  location: class StatusChangeRecorder
/data/git_workspace/azkaban/azkaban-exec-server/src/test/java/azkaban/dag/StatusChangeRecorder.java:41: error: cannot find symbol
  void verifySequence(final List<Pair<String, Status>> expectedSequence) {
                                 ^
  symbol:   class Pair
  location: class StatusChangeRecorder
Note: /data/git_workspace/azkaban/azkaban-exec-server/src/test/java/azkaban/execapp/AzkabanExecutorServerTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

> Task :azkaban-solo-server:compileJava 
Note: /data/git_workspace/azkaban/azkaban-solo-server/src/main/java/azkaban/soloserver/AzkabanSingleServer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
anyone help to fix it, thanks a lot .

**Comment by HappyRay** [comment]
I can compile with the same JDK fine.

**Comment by modeyang** [comment]
issue solved!  need **java-openjfx** jre lib.  related issue [java.lang.ClassNotFoundException: javafx.util.Pair](https://gist.github.com/androidfred/bc64da9e6a355b984d37439ed63ae16b)

**Comment by zhenghao0379** [comment]
> issue solved! need **java-openjfx** jre lib. related issue [java.lang.ClassNotFoundException: javafx.util.Pair](https://gist.github.com/androidfred/bc64da9e6a355b984d37439ed63ae16b)

遇到的同样的问题，url不能打开了。这个怎么解决啊

**Comment by vhermecz** [comment]
A had a similar issue, with `error: package javafx.util does not exist`.
Turns out that openjfx now has a v11 which is "incompatible" with jdk8. (Incompatible as in it enforces using the module system, and if a codebase was not using that, it breaks).

See details about it here: https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946

One workaround is to specify version 8 and mark hold the packages. **NOTE: This introduces the security risk of these packages not being updated anymore.**

https://bugs.launchpad.net/ubuntu/+source/openjfx/+bug/1799946/comments/20
```
sudo apt install \
  openjfx=8u161-b12-1ubuntu2 \
  libopenjfx-java=8u161-b12-1ubuntu2 \
  libopenjfx-jni=8u161-b12-1ubuntu2
sudo apt-mark hold \
  openjfx \
  libopenjfx-java \
  libopenjfx-jni
```

**Comment by shcent** [comment]
I suspect and easier fix would be to remove the dependency on javafx all together. The only need appears to be for the Pair class. This is also available in apache commons-lang3. Replacing Pair with ImmutablePair in these two tests (and adding the dependency) did the trick. Now compiles and runs with no issues.

Replace javafx.util.Pair with org.apache.commons.lang3.tuple.ImmutablePair (has to be ImmutablePair as Pair is abstract) and obviously need to add dependency to 'org.apache.commons:commons-lang3:3.10'

**Comment by zencore-cn** [comment]
Use jdk download from oracle site instead of openjdk. It's just works fine with oracle jdk.

**Comment by rozhok** [comment]
This thing prevents building Docker image using `openjdk:8-buster` as base, because buster includes openjfx version 11 which seems to be incompatible with openjdk 8

As a workaround one can build azkaban from sources skipping tests.

**Comment by shcent** [comment]
> Use jdk download from oracle site instead of openjdk. It's just works fine with oracle jdk.

The code should work with openjdk as well. A very small change the the unit tests makes the code work with openjdk. Seems crazy to me to build in a dependency that really is not needed.
