### ISSUE TITLE
Configure to kill a job or flow that is timeout

### ISSUE THREAD

**Issue by Vimos** [azkaban/azkaban#2086]
For some jobs we are scheduling, we might need to kill it when it exceeds a time limit. Of course, we can write it down in our scripts. How about adding a configuration property supporting timeout job killing?

**Comment by archongum** [comment]
`timeout -k 5 120 [command]` just fine.
> timeout sends TERM signal after the 120 seconds. If command didn't respond to TERM then sends KILL signal after 5 more seconds
