### ISSUE TITLE
How to change the default value of "Failure Options"?

### ISSUE THREAD

**Issue by archongum** [azkaban/azkaban#2092]
![snipaste_2019-01-14_09-33-36](https://user-images.githubusercontent.com/20929338/51093529-7899c500-17df-11e9-9523-cadecfcffdf7.png)

How to change the default value of "Failure Options", is there a parameter for this such as `failure.action=FINISH_ALL_POSSIBLE` for schedulers? or jobs? or projects?

I know AJAX API has this parameter

![snipaste_2019-01-14_09-37-58](https://user-images.githubusercontent.com/20929338/51093584-1f7e6100-17e0-11e9-84b5-d179f5ab9f48.png)

Please help me out

**Comment by vickyi** [comment]
@archongum my flow config like this:
`config:
  failure.emails: zhangjiqiang@icsoc.net
  failure.action: FINISH_ALL_POSSIBLE`

**Comment by archongum** [comment]
> @archongum my flow config like this:
> 
> ```
> config:
>   failure.emails: myemailname@xxxx.net
>   failure.action: FINISH_ALL_POSSIBLE
> ```

yeah. It works in `azkaban-flow-version: 2.0` mode. 

Unfortunately it doesn't work in old version by setting `failure.action=FINISH_ALL_POSSIBLE`

**Comment by archongum** [comment]
emm, it works by just changing `Failure Options` and then schedule.

![snipaste_2019-02-26_17-40-43](https://user-images.githubusercontent.com/20929338/53403187-2064fe00-39ee-11e9-85e0-d7fd7df8118e.jpg)
![snipaste_2019-02-26_17-41-11](https://user-images.githubusercontent.com/20929338/53403188-2064fe00-39ee-11e9-8c9c-1c9eac760a46.jpg)
![snipaste_2019-02-26_17-42-19](https://user-images.githubusercontent.com/20929338/53403190-2064fe00-39ee-11e9-91d3-13d566aa6e8e.jpg)
