### ISSUE TITLE
how to use  kafka-event-trigger  ?

### ISSUE THREAD

**Issue by jacyyu1988** [azkaban/azkaban#2101]
at  the   link :   'https://azkaban.readthedocs.io/en/latest/eventTrigger.html#event-based-trigger-plugin-configuration'

it says:
Inside the **Azkaban dependency plugin directory**, there should be two items Event Based Trigger plugin jar and the **dependency.properties**.
....

but  where is the 'Azkaban dependency plugin directory'  and  'dependency.properties'   . or where should  I  create  it . 

who  can tell me  ,  give me a example of dependency.properties.  

thank you  very much!

**Comment by Kaoxyd** [comment]
You should compile the kafka-event-trigger plugin first. Then, a bit of configuration is needed
azkaban.properties
```
`executor.metric.reports=true
azkaban.server.schedule.enable_quartz=true
azkaban.dependency.plugin.dir=plugins/deps

org.quartz.dataSource.quartzDS.driver=org.h2.Driver
org.quartz.dataSource.quartzDS.URL=jdbc:h2://.h2/quartzDS
org.quartz.threadPool.threadCount=4
```
(Enabling Quartz seems mandatory in that case. Change the jdbc driver following your database kind)

Then, your plugin dir must be containing something like 
```
- plugins
--- deps
----- kafka
------- dependency.properties
------- kafka-plugin.jar
--- jobtypes
----- ...
```

The kafka-plugin.jar must be the jar compiled before. Then, your dependency.properties must contain

```
dependency.class=trigger.kafka.KafkaDependencyCheck
dependency.classpath=plugins/deps/kafka/kafka-plugin.jar
```

That's enough I think

**Comment by jacyyu1988** [comment]
Thanks you for your help. according to your description, I have solved my problem.thank you very much.
