### ISSUE TITLE
az-hadoop-jobtype ['hadoopJava' is unrecognized]

### ISSUE THREAD

**Issue by zak000** [azkaban/azkaban#2125]
Hello,

- I tried to install the hadoopjava plugin in Azkaban 3.57, the problem is when i upload a test job juste with the type = hadoopJava it says : Failed to build job executor for job testJob type 'hadoopJava' is unrecognized
 
17-02-2019 02:18:55 CET test INFO - Starting job test at 1550366335156
17-02-2019 01:32:56 CET test INFO - Starting job test at 1550363576301
17-02-2019 01:32:56 CET test INFO - azkaban.webserver.url property was not set
17-02-2019 01:32:56 CET test INFO - job JVM args: -Dazkaban.flowid=test -Dazkaban.execid=140690 -Dazkaban.jobid=test
17-02-2019 01:32:56 CET test INFO - user.to.proxy property was not set, defaulting to submit user azkaban
17-02-2019 01:32:56 CET test INFO - Building hadoopJava job executor. 
17-02-2019 01:32:56 CET test ERROR - Failed to build job executor for job testJob type 'hadoopJava' is unrecognized

Contente of my job.test:
type=hadoopJava

- When i check the logs of my executor i don’t see any error and its says that the security manager was uploaded and the kerberos authentication is up and running for the executor

executor logs : 

2019/02/17 02:00:35.861 +0100 INFO [HadoopSecurityManager_H_2_0] [Azkaban] Using principal from my_user and path_to_my_keytab
2019/02/17 02:00:36.295 +0100 DEBUG [UserGroupInformation] [Azkaban] hadoop login
2019/02/17 02:00:36.299 +0100 DEBUG [UserGroupInformation] [Azkaban] hadoop login commit
2019/02/17 02:00:36.301 +0100 DEBUG [UserGroupInformation] [Azkaban] using kerberos user:my_user@my_domaine
2019/02/17 02:00:36.301 +0100 DEBUG [UserGroupInformation] [Azkaban] Using user: "my_user@my_domaine" with name my_user@my_domaine
2019/02/17 02:00:36.302 +0100 DEBUG [UserGroupInformation] [Azkaban] User entry: "my_user@my_domaine"
2019/02/17 02:00:36.303 +0100 INFO [UserGroupInformation] [Azkaban] Login successful for user my_user using keytab file path_to_my_keytab
2019/02/17 02:00:36.303 +0100 INFO [HadoopSecurityManager_H_2_0] [Azkaban] Logged in with user my_user@my_domaine (auth:KERBEROS)
2019/02/17 02:00:36.304 +0100 INFO [HadoopSecurityManager_H_2_0] [Azkaban] Hadoop Security Manager initialized
2019/02/17 02:00:36.304 +0100 INFO [JobTypeManager] [Azkaban] Loaded jobtype hadoopJob azkaban.jobtype.HadoopJavaJob

- This is the content of my commonprivate.properties

hadoop.security.manager.class=azkaban.security.HadoopSecurityManager_H_2_0
proxy.keytab.location=/path_to_my_keytab
proxy.user=user_proxy
azkaban.should.proxy=true
obtain.binary.token=true
allow.group.proxy=true
hadoop.home=home_of_the_hadoop_installation
hadoop.conf.dir=home_of_the_hadoop_installation/etc/hadoop/conf
jobtype.global.classpath=${hadoop.home}/jars/hadoop-core-2.6.0-mr1-cdh5.16.1.jar,path_to_my_execserver_install/plugins/jobtypes/hadoopJob/lib/az-hadoop-jobtype-plugin-3.57.0.jar,path_to_my_execserver_install/lib,path_to_my_execserver_install/plugins/jobtypes/hadoopJob/lib/

- The content of my common.properties

hadoop.home=home_of_the_hadoop_installation
jobtype.global.classpath=${hadoop.home}/jars/hadoop-core-2.6.0-mr1-cdh5.16.1.jar,path_to_my_execserver_install/plugins/jobtypes/hadoopJob/lib/az-hadoop-jobtype-plugin-3.57.0.jar,path_to_my_execserver_install/lib,path_to_my_execserver_install/plugins/jobtypes/hadoopJob/lib/
azkaban.should.proxy=true

- In the lib directory of my executor i pul the azkaban-hadoopsecuritymanager and az-hadoop-jobtype plugins

**Comment by zak000** [comment]
Hello all,

The name of the plugin was not correct, i changed it to match exactly the name of plugin (hadoopJava) and now it works.

Thank you

**Comment by LongStockingPipi** [comment]
I'm blind? With all due respect, I don't see any difference between before and after

**Comment by LongStockingPipi** [comment]
Not sure how you solved it
