### ISSUE TITLE
3.69.0 exec-server with poll model polling service can not get execution flow from db

### ISSUE THREAD

**Issue by lecterqian** [azkaban/azkaban#2149]
I insert a test data into table 'execution_flows' manually, when i start exec-server with polling model alone,it fetch prepare data from table 'execution_flows',but it can not fetch data because 'active' is false default whtin class 'FlowRunnerManager' ,if set active is true,then ok.But 'active' is only set by method 'handleRequest' whtin class ‘ExecutorServlet’,and this servlet should be called by web-server ,but web-server will not call http request to exec-server in  new design,this question confuse me. Thanks.

**Comment by burgerkingeater** [comment]
hi @lecterqian  
To activate an executor, one can just call "executor host:executor port/executor?action=activate" on executor host, and it doesn't require http request from web server.
```but web-server will not call http request to exec-server``` ,  in fact web server will still need to talk to executor in the new design to fetch execution logs, kill executions, etc.

**Comment by lecterqian** [comment]
@burgerkingeater 
1. thanks,I modify column "active" from 0 to 1 in table "executors" in old desgin ,and method "createFlowRunner" do not need "active",used in 3.69.0.
Because i think one executor data have been inserted,it should be active,and it troubles by using this call "executor host:executor port/executor?action=activate",may be web-server can show all executors, then user can choose executor to enable,after all, may be some user is not  programmer,and they do not know commands like "curl".
2. Database lock used in new desgin, "select for update" used like Quartz, I find do much for realse db lock in Quartz, why do not use other distributed lock, and if use db lock, db server will grow pressures when have much jobs to schedule, because web-server and executor-server will do much with db.
why do not save not complete flow and job in db like redis, when flow complete then save to database,db just save flow and job info and final status of them like sucess  or fail.
