### ISSUE TITLE
Big fat flow load grahp too slow ....

### ISSUE THREAD

**Issue by kqixiang945** [azkaban/azkaban#2177]
Our team currently uses only one Flow in a Project. But there are nearly 4,000 tasks in our Flow. When to be run Flow or when viewing the historical tasks of this Flow, opening the page is very, very slow. Even now the browser memory is full and hangs.  The reason for this is the formation of a dependency graph.  Is there any solution or workaround for the too big flow.....

**Comment by kqixiang945** [comment]
@burgerkingeater

**Comment by kqixiang945** [comment]
@burgerkingeater Hi ,I hope you can help me give me an workaround...

**Comment by burgerkingeater** [comment]
Hi @kqixiang945 thanks for reporting this. We don't have a good workaround except breaking the flow into smaller pieces(usually level of several hundreds is acceptable, but 4000 is far beyond what I have seen).

**Comment by kqixiang945** [comment]
@burgerkingeater Thank you very much for your answer. We are going to turn SVG Graph into a joblist, and the corresponding menu(Disable,Enable and so on ) of the right mouse button is made into the corresponding button to solve big fat flow load grahp too slow problem....
