### ISSUE TITLE
Scheduling multiple flows at once via API

### ISSUE THREAD

**Issue by toby-allsopp** [azkaban/azkaban#2190]
Is there a way to do a bulk schedule of multiple flows with a single API call? At the moment I'm calling `fetchSchedule` then `removeSched` then `scheduleCronFlow` for each flow in the project and it's quite slow for a lot of flows. I'd like a way to include the schedule in the project zip file ideally.

Any ideas?

**Comment by burgerkingeater** [comment]
@toby-allsopp  yes, it's doable, take a look at `flow trigger` in azkaban doc. Basically it allows user to define the schedule as part of flow configuration.

**Comment by toby-allsopp** [comment]
Thank you, I will take a look. I had previously dismissed that feature as something to do with Kafka.

**Comment by burgerkingeater** [comment]
Actually it doesn’t , take a look at document and let us know if there’s
any question

**Comment by toby-allsopp** [comment]
It works! If I don't specify any dependencies then I don't need to install a dependency plugin.

I found I needed to add the following lines to `azkaban.properties` - is this expected?

```
azkaban.server.schedule.enable_quartz=true
org.quartz.threadPool.threadCount=10
azkaban.dependency.plugin.dir=plugins
```

**Comment by toby-allsopp** [comment]
Is there any way to set a SLA for a flow trigger?

**Comment by burgerkingeater** [comment]
not yet, do you want to contribute?

**Comment by toby-allsopp** [comment]
> not yet, do you want to contribute?

I will investigate this to see how much work it is. So far I have failed to understand how the SLA feature works :). We will almost certainly use flow triggers instead of schedules because we can potentially use the dependency feature to support dependencies between flows, which is a feature we require.
