### ISSUE TITLE
What's a TriggerPlugin?

### ISSUE THREAD

**Issue by toby-allsopp** [azkaban/azkaban#2252]
I can't find any code that uses any of the methods in the `TriggerPlugin` interface - is this dead code or a yet-to-be-implemented feature or am I missing something?

**Comment by burgerkingeater** [comment]
it was code from an aborted feature.

**Comment by toby-allsopp** [comment]
Aha, thank you! I will happily ignore it. Would you be interested in a PR to remove it?

**Comment by burgerkingeater** [comment]
Sure , I would like to review it.
