### ISSUE TITLE
I have a flow that has more than 100jobs. What is the best practices. 100jobs in one flow file?

### ISSUE THREAD

**Issue by deadwind4** [azkaban/azkaban#2273]

**Comment by lampjian** [comment]
If there is no dependency between your jobs, you should take the best use of all machines with parallel flow jobs.

**Comment by deadwind4** [comment]
> If there is no dependency between your jobs, you should take the best use of all machines with parallel flow jobs.

**Comment by deadwind4** [comment]
There are all dependency between my jobs.

**Comment by deadwind4** [comment]
I think I need redesign my system logic

**Comment by dongwuyong** [comment]
What's the best way to do it?
