### ISSUE TITLE
Project creation via API fails with "Missing required parameter 'project'" on 3.73.1

### ISSUE THREAD

**Issue by steverding** [azkaban/azkaban#2310]
Just did the following via API (in python):

#This is for disabling certificate checks:
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

#filling a dictionary with the required parameters. 
fields = {'session.id': sessionid, 'ajax': 'create', 'action': 'create', 'name': 'TESTPROJECT', 'description': 'Testproject'}
#urlencoding the parameters
urlencdat=urllib.urlencode(fields)
#Building a request and sending it
request = urllib2.Request("https://localhost:8443/manager", data=urlencdat)
f = urllib2.urlopen(request,context=ctx)

urllib2.HTTPError: HTTP Error 500: Missing required parameter 'project'.

This worked in azkaban 3.57 but throws this exception in 3.73

**Comment by ypadron-in** [comment]
Hi @steverding,

The 'ajax=create' parameter is what's causing the error, please remove it. You should be able to create the project after that.
