### ISSUE TITLE
Is it possible to run job on different executor on same flow?

### ISSUE THREAD

**Issue by anantmf** [azkaban/azkaban#2327]
Hi,

Is it possible to run job on different executor on same flow?
We have a flow with multiple parallel jobs, but they all are run on same executor, can we distribute that?

Thanks.
Regards,
Anant.

**Comment by ypadron-in** [comment]
Hi @anantmf,
It's not possible to execute some jobs from one flow in one executor and the rest in another. 
The executor server will run concurrently (up to a configurable number) all the jobs that can be run (those with their dependencies met).
