### ISSUE TITLE
How can I know which executor has no running job?

### ISSUE THREAD

**Issue by AronChung** [azkaban/azkaban#2464]
when I deactivate an executor, as we know it can not interrupt running jobs, then I want to shutdown this process.  How can I know this executor has no running job ?

**Comment by svnarumugam** [comment]
Hi @AronChung , you can check that by using the jmx status that is exposed through the webserver. Access the /jmx path in webserver. For example, webserver:<port>/jmx and check the FlowRunnerManager. That should give the list of running flows.

**Comment by AronChung** [comment]
> Hi @AronChung , you can check that by using the jmx status that is exposed through the webserver. Access the /jmx path in webserver. For example, webserver:/jmx and check the FlowRunnerManager. That should give the list of running flows.

get it! thanks!!! @svnarumugam
