### ISSUE TITLE
Too big h2.mv.db and is that a problem?

### ISSUE THREAD

**Issue by zhongyi-peng** [azkaban/azkaban#2469]
we have used azkaban  about 4 month and found that the h2.mv.db file is so big.
Is this a problem need to be solved?
How can we reduce the size of h2?
and is there any way to transform into mysql?
many thanks!

# ls -lrth
total 65G
-rwx------   1 hive root  65G Mar 11 14:59 h2.mv.db

**Comment by djaiswal83** [comment]
I would use mysql as it can scale well compared to h2.
Are you storing project zips in the db? Azkaban allows use of hdfs to do that.
To transform to mysql, there maybe a small downtime where after creating the schema, you perform ETL.
