### ISSUE TITLE
Change builded from 0.1.0-SNAPSHOT to other

### ISSUE THREAD

**Issue by rafilkmp3** [azkaban/azkaban#2475]
someone know how change the version from 0.1.0-SNAPSHOT to another version on builded version ? like 3.84.0 on login screen 

![image](https://user-images.githubusercontent.com/12433667/77197318-bec57500-6ac3-11ea-913d-2596c40f2fa3.png)

**Comment by yorix2009** [comment]
open file build.gradle, add version=x.x.x

for example:
=================
allprojects {
  apply plugin: 'jacoco'
  **version '3.81.0'**
  repositories {
    mavenCentral()
    mavenLocal()
  }
}

**Comment by rafilkmp3** [comment]
thanks a lot @yorix2009
