### ISSUE TITLE
does azkaban support change azkaban.properties without restart webserver

### ISSUE THREAD

**Issue by litao3rd** [azkaban/azkaban#2573]
Hi, there. I'm a newbee of azkaban.  I'm trying deploy an azkaban service in my work. So I need change content in azkaban.properties frequently. I need restart the azkaban web server process to make the change effective. I wonder if there is any method like `reloadExecutors ` to force reload the properties file.

**Comment by hqin2016** [comment]
Currently there's no such option.

**Comment by litao3rd** [comment]
looking forward it
