### ISSUE TITLE
How to kill spark job on yarn by azkaban?

### ISSUE THREAD

**Issue by JoaNIO** [azkaban/azkaban#2648]
when I launch spark job on yarn by azkaban，I find that it cannot kill spark job on yarn by azkaban's kill function. It seems that azkaban can only kill job on its executor server. So how can i kill such spark job on yarn launched by azkaban, is there anyone can help this?

**Comment by JoaNIO** [comment]
I solved it

**Comment by ighack** [comment]
@JoaNIO How can you fix it.
