### ISSUE TITLE
Single future execution time of a flow

### ISSUE THREAD

**Issue by hellofantastic** [azkaban/azkaban#2665]
Hello all,

Does the Azkaban api support sending in a datetime string  to execute a flow once in the future?
I see Schedule a period-based Flow (Deprecated) may have been the option but deprecated, when is it completely out?
Is there a replacement for one time like say the SimpleTrigger piece of Quartz Scheduler?

**Comment by djaiswal83** [comment]
Hi,

As of now it does not. However, I think this can be achieved using the cron expression if you use specific values instead of wild card entries.

**Comment by hellofantastic** [comment]
Okay thank you, I could experiment with your suggestion but also the deprecated one still works and our need for it will only be for a couple months before going completely event based and not time dependent.
