### ISSUE TITLE
how to executor SQLPlus?

### ISSUE THREAD

**Issue by riritack** [azkaban/azkaban#2672]
when run then shell what contain sqlpuls it will have error like:
/opt/oracle/instantclient_19_9/sqlplus: error while loading shared libraries: libsqlplus.so: cannot open shared object file: No such file or directory

executor "chmod 777 libsqlplus.so" has no effective

**Comment by caviarbag** [comment]
Have you set `LD_LIBRARY_PATH=/opt/oracle/instantclient_19_9;` before executing sqlplus?

**Comment by riritack** [comment]
> Have you set `LD_LIBRARY_PATH=/opt/oracle/instantclient_19_9;` before executing sqlplus?

yes，I can run without Azkaban

**Comment by caviarbag** [comment]
Ok, I dont know how to help you further. You need to find a way to set this environmentvariable in Azkaban startupscript. Other options are in the job-files or globally on host. But this is definately not an Azkaban issue/problem.
