### ISSUE TITLE
upload zip file error

### ISSUE THREAD

**Issue by jerryofouc** [azkaban/azkaban#29]
when I upload the flow the correct zip file using my Chrome and Firefox, I comes the  
"File type application/octet-stream unrecognized.",I seems that the post the brower does not recognize the zip file as application/octet-stream(http://stackoverflow.com/questions/856013/mime-type-for-zip-file-in-google-chrome). I think it is a bug.

**Comment by bugbeta** [comment]
新版本 3.59 仍遇到这问题，只能把 .zip 文件的后缀 .zip 删除，可以正常上传。

**Comment by bugbeta** [comment]
File type application/x-compressed unrecognized.
