### ISSUE TITLE
API Problem: Executing flow

### ISSUE THREAD

**Issue by ghost** [azkaban/azkaban#31]
The 'execute flow' API gives no error, but does not start a flow. 'job1' is a job in the project, and I can start it by hand. The API does not start it.

[my machine]$  curl -D headers -k --data 'action=executeFlow&session.id=2ead5140-2668-4891-be58-d84e6c00827a&project=api_test&flow=job1' https://localhost:8443
[my machine]$ cat headers
HTTP/1.1 200 OK
Content-Length: 0
Server: Jetty(6.1.26)

**Comment by davidzchen** [comment]
This should be possible to do now (http://azkaban.github.io/azkaban/docs/2.5/#api-execute-a-flow). Please reopen if you are still experiencing this problem.
