### ISSUE TITLE
Python job-type does not have access to JOB_PROP_FILE and JOB_OUTPUT_PROP_FILE

### ISSUE THREAD

**Issue by artxgj** [azkaban/azkaban#319]
We can't use a Python job-type to receive data from a previous job or send data to the next job. 

LongArgJob's run method always returns a zero for builder.getEnv().size (line 65). My guess is the culprit is in the constructor, which sets the builder member variable without first calling initPropFiles(). 

  public LongArgJob(String jobid, String[] command, Props sysProps,
      Props jobProp, Logger log, Set<String> suppressedKeys) {
    super(jobid, sysProps, jobProp, log);

```
this.builder =
    new AzkabanProcessBuilder(command)
        .setEnv(getJobProps().getMapByPrefix(ENV_PREFIX))
        .setWorkingDir(getCwd()).setLogger(getLog());
appendProps(suppressedKeys);
```

  }

LongArgJob does call initPropFiles() in its run method. 

My guess regarding this bug is based on looking at ProcessJob's run method's lines 67-102 and comparing them to LongArgJob's run method. Lines 67-10-2 of ProcessJob's run method are:

```
File[] propFiles = initPropsFiles();
Map<String, String> envVars = getEnvironmentVariables();

for (String command : commands) {
  info("Command: " + command);
  AzkabanProcessBuilder builder =
      new AzkabanProcessBuilder(partitionCommandLine(command))
          .setEnv(envVars).setWorkingDir(getCwd()).setLogger(getLog());

  if (builder.getEnv().size() > 0) {
    info("Environment variables: " + builder.getEnv());
  }
  info("Working directory: " + builder.getWorkingDir());

  boolean success = false;
  this.process = builder.build();

  try {
    this.process.run();
    success = true;
  } catch (Throwable e) {
    for (File file : propFiles)
      if (file != null && file.exists())
        file.delete();
    throw new RuntimeException(e);
  } finally {
    this.process = null;
    info("Process completed "
        + (success ? "successfully" : "unsuccessfully") + " in "
        + ((System.currentTimeMillis() - startMs) / 1000) + " seconds.");
  }
}

// Get the output properties from this job.
generateProperties(propFiles[1]);
```

  }

**Comment by HappyRay** [comment]
Python job type is not documented http://azkaban.github.io/azkaban/docs/latest/#job-types.
Can you command job type work for you?

If there is no sufficient reason to maintain these job types, it would be easier to maintain fewer job types. This is an example of maintenance cost.

**Comment by sjakthol** [comment]
I don't remember if there was any particular reason to use python jobs instead of command jobs. Most likely the functionality of python (and any of the other extra job types) can be implemented as pure command jobs.

More generally, we would be happy to get rid of these extra job types as they are always executed as the user running the azkaban executor which gives users pretty much the rights to do anything they want. At least the command type jobs can be limited a bit with the execute-as-user functionality offered there.

**Comment by HappyRay** [comment]
We are removing these job types. #1431
