### ISSUE TITLE
When upload big zip file, got error

### ISSUE THREAD

**Issue by sunjianqing** [azkaban/azkaban#32]
When I uploaded zip file which is more than 100mb, I got 

"Installation Failed.
Error chunking"

**Comment by dwatzke** [comment]
When uploading a bigger project zip file, I got the mentioned chunking error & this exception popped up in the web server log:

java.sql.SQLException: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.

So naturally increasing innodb_log_file_size has helped. Here's an official howto : http://dev.mysql.com/doc/refman/5.5/en/innodb-data-log-reconfiguration.html
