### ISSUE TITLE
[Feature Request] ability to deploy/undeploy jobs via API 

### ISSUE THREAD

**Issue by patricioe** [azkaban/azkaban#34]
Please ignore this request if such a feature already exists.

I'd be good to have an API that allows job manipulation such us deploy, undeploy, run, stop, etc.

We are interesting in auto-deployments of jobs driven by our build server.

Thanks.

**Comment by HappyRay** [comment]
I think we do now. See http://azkaban.github.io/azkaban/docs/latest/#ajax-api
Please let us know if that's not enough.
