### ISSUE TITLE
Is it possible to run streaming MR jobs using Azkaban?

### ISSUE THREAD

**Issue by afarnoosh** [azkaban/azkaban#366]
My use case involves running streaming jobs on my cluster. Can you guys point me to a plug-in or guide me on how to enable this for my deployment?

Thanks!

**Comment by vikramkone** [comment]
+1 .. Does Azkaban support long running jobs like spark streaming jobs etc? If we use the command job type and kick off a spark submit command that starts a never ending spark streaming job..does azkaban kill it or let it be?

**Comment by zpappa** [comment]
+1 I don't see this answered anywhere and have the same question.
