### ISSUE TITLE
Support the ability to download project zip file

### ISSUE THREAD

**Issue by hluu** [azkaban/azkaban#373]
Currently there is no way to retrieve back the upload project zip file.

**Comment by jsharley** [comment]
Are there plans to add this functionality to the AJAX API?

**Comment by erwa** [comment]
If you look at the change, it seems to be calling a REST API: https://github.com/hluu/azkaban2/commit/a9d832e50068b15da3176dec891ada72119c07a4#diff-b646b1e6590b8b22e25a009cbf141e51R140

You should be able to use this programmatically. It just hasn't been added to the Azkaban documentation, yet.

**Comment by erwa** [comment]
We would also be very happy to accept a pull request to update the documentation :-). See the "Documentation" section on [this page](https://github.com/azkaban/azkaban) for instructions on updating it.

**Comment by badbye** [comment]
Still no document about it?

**Comment by porthunt** [comment]
In case there is anyone interested:
```python
url = "http://example.com:8081/manager"
params = {
    "project": "foobar",
    "download": "true",
    "session.id": "sessionid"
}

with requests.get(url, params=params, stream=True) as r:
        r.raise_for_status()
        with open(filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192): 
                if chunk:
                    f.write(chunk)
```
