### ISSUE TITLE
Property to override smtp port in azkaban.properties

### ISSUE THREAD

**Issue by sathish316** [azkaban/azkaban#394]
While sending emails using smtp.gmail.com, the port number should be 587, but Azkaban uses default port of 25 which doesn't work. Can you please provide a property mail.port which can be passed as mail.smtp.port in EmailMessage#sendEmail?

**Comment by hyurtseven81** [comment]
+1

**Comment by ismailsimsek** [comment]
+1

**Comment by sathish316** [comment]
There is a Pull request open for this - https://github.com/azkaban/azkaban/pull/395

**Comment by HappyRay** [comment]
#872
