### ISSUE TITLE
Support job URL call back

### ISSUE THREAD

**Issue by hluu** [azkaban/azkaban#442]
Currently Azkaban can send email notification upon job completion (success or failure).  This feature is for Azkaban to make URL call back to make it easier to send job status to external system for monitoring use cases and other use cases.

### HTTP Callback URL
Each user job can optionally specify one or more HTTP callback URLs for Azkaban to call when a job is started or completed.  
A new property will be introduced to specify one or more callback URLs.  Below is the proposed format.
job.notification.<status>.<sequence number>.url=<url>
status:  [started | success | failure | completed]
started => when job is started
success => when a job is successfully completed
failure => when a job completed, but failed
completed => when a job is either successfully completed or failed
A HTTP URL callback can be either a GET or POST, below is the property for the request method
job.notification.<status>.<sequence number>.method=<request method>
request method: [GET | POST]
GET => Azkaban will use HTTP GET method for HTTP call.  
POST => Azkaban will use HTTP POST method for HTTP call.
If the method is not specified, then GET request method will be used
When a POST request method is specified, then the body must specified as well.  The property for the body is:
job.notification.<status>.<sequence number>.body=<body text>
sequence number: this is to specify 1 or more URLs and there shouldn't any gap in the sequence.
The maximum # of callback URLs per job is 3.
Each job callback URL can optional specify headers in the following format
job.notification.<status>.<sequence number>.headers=<name>:<value>\r\n<name>:<value>
The delimiter for each header is \r\n and delimiter between header name and value is ':'
The headers are applicable for both GET and POST job callback URLs.
### Job context information
It is often desirable to include some dynamic context information about the job in the URL or POST request body, such as status, job name, flow name, execution id and project name.
If the URL or POST request body contains any of the following tokens, they will be replaced with the actual values by Azkabn before making the HTTP callback is made. The value of each token will be HTTP encoded when GET method request is specified.
?{server} - Azkaban host name and port
?{project}
?{flow}
?{executionId}
?{job}
?{status} - possible values are started, failed, succeeded

**Comment by hluu** [comment]
The implementation is done, just need to update the documentation

**Comment by hluu** [comment]
Documentation has been udpated

**Comment by xFaris** [comment]
how to use it?

**Comment by daksh-talwar** [comment]
> Documentation has been udpated

How can I access the documentation? Is the first comment on this issue the official doc for this feature?

**Comment by HappyRay** [comment]
Search for "HTTP Job Callback" in the doc
https://azkaban.github.io/azkaban/docs/latest/#common-configurations

**Comment by zzz24512653** [comment]
How can I tell Failed or Killed from failure status?

**Comment by juhoautio** [comment]
Killed & Failed are both notified according to the `failure` callback.

You can include the actual status in callback params, for example:

	job.notification.failure.1.body=[?{status}] ?{project}: ?{flow}

Would be formatted to either:

	[killed] myproject: myflow

or:

	[failed] myproject: myflow

----

I think it would be nice to support separate callback conf for killed status though. Eg.:

- `job.notification.killed` for KILLED only
- `job.notification.failed` for FAILED only
- `job.notification.unsuccessful` for any finished status != SUCCESS
- `job.notification.failure` _deprecated_, but supported for backward compatibility (for KILLED or FAILED)

@HappyRay what do you think?
