### ISSUE TITLE
Provide High availability to Azkaban master with Zookeeper?

### ISSUE THREAD

**Issue by vikramkone** [azkaban/azkaban#461]
Hi,
Current Azkaban setup has a SPOF for the Master server and this doesn't work for large cluters that have nodes constantly failing over. Are there plans to integrate Azkaban with zookeper to provide HA for Azkaban?

**Comment by powershot29** [comment]
We are also facing the same problems. How did you end up working around that?

**Comment by vikramkone** [comment]
When is 4.0 releasing and are there any docs on what the new features are?

**Comment by ameyamk** [comment]
4.0 won't have this feature but 4.x will have it. Here is the roadmap: https://github.com/azkaban/azkaban/wiki/Azkaban-4.x--Roadmap
