### ISSUE TITLE
Job failed, Cannot request memory (Xms 0 kb, Xmx 0 kb) from system for job

### ISSUE THREAD

**Issue by letusfly85** [azkaban/azkaban#481]
I cloned azkaban `master` branch, and run `build distTar`,
(some test steps failed,,, so I skipped)

after then, I started `bin/azkaban-solo-start.sh`.

I created a project and a job like below.

```
type=command
command=echo "Hello World"
```

However, I executed this job, I got below...

How can I fix `Cannot request memory (Xms 0 kb, Xmx 0 kb) from system for job`  ?

```
06-09-2015 18:39:49 PDT hello INFO - Starting job hello at 1441589989035
06-09-2015 18:39:49 PDT hello INFO - azkaban.webserver.url property was not set
06-09-2015 18:39:49 PDT hello INFO - job JVM args: -Dazkaban.flowid=hello -Dazkaban.execid=15 -Dazkaban.jobid=hello
06-09-2015 18:39:49 PDT hello INFO - Building command job executor. 
06-09-2015 18:39:49 PDT hello ERROR - Job run failed!
java.lang.Exception: Cannot request memory (Xms 0 kb, Xmx 0 kb) from system for job hello
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:63)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:590)
	at azkaban.execapp.JobRunner.run(JobRunner.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
06-09-2015 18:39:49 PDT hello ERROR - Cannot request memory (Xms 0 kb, Xmx 0 kb) from system for job hello cause: null
06-09-2015 18:39:49 PDT hello INFO - Finishing job hello attempt: 0 at 1441589989048 with status FAILED
```

**Comment by letusfly85** [comment]
I found that system requirement is at least 3GB memory for azkaban.

After I changed an instance type on AWS from t2.medium to r3.large, it solved...

Sorry :sweat_drops: 

Thank you.

**Comment by juhoautio** [comment]
If you don't need 3GB free memory for some simple shell commands, you can also disable the memory check by setting `memCheck.enabled=false` in `plugins/jobtypes/commonprivate.properties`.

**Comment by WillCup** [comment]
got the same problem from 2.6.4.... memory is not enough, but the memCheck.enabled=false does not work either.....
there is nothing in my plugins dir, is it correct? I just run the hello word demo

**Comment by binhnv** [comment]
@WillCup There was a bug in previous version of Azkaban (<3.0) in JobTypeManager.buildJobExecutor which caused the `memCheck.enabled=false` has no effect. This is fixed in later version.
You just need to create a file named commonprivate.properties in plugins/jobtypes, add your setting and then restart executor server.

**Comment by SnailSjw** [comment]
Note:这种方法的解决办法就是在  azkaban/exec-server/plugins/jobtypes/commonprivate.properties文件中添加`memCheck.enable=false`

**Comment by jast90** [comment]
> If you don't need 3GB free memory for some simple shell commands, you can also disable the memory check by setting `memCheck.enabled=false` in `plugins/jobtypes/commonprivate.properties`.

Not work for me , My azkaban version is 3.90.0
