### ISSUE TITLE
Newer browsers cannot access Azkaban web server because of Logjam vulnerability

### ISSUE THREAD

**Issue by nomorogbe** [azkaban/azkaban#483]
The SSL Logjam vulnerability (https://weakdh.org/) was present in Jetty on our Azkaban servers.

For example, Azkaban pages failed to load on Firefox Browsers 39 and up.
Error code: ssl_error_weak_server_ephemeral_dh_key

We are running Azkaban 2.6.1.

We successfully patched our local servers by making the two changes below.
If the latest Azkaban has the same issue, can these changes be integrated into the latest sources?

azkaban/azkaban-webserver/src/main/java/azkaban/webapp/AzkabanWebServer.java

      SslSocketConnector secureConnector = new SslSocketConnector();
      ...
      // set up vulnerable cipher suites to exclude
      List<String> cipherSuitesToExclude = azkabanSettings.getStringList("jetty.excludeCipherSuites");
      logger.info("Excluded Cipher Suites: " + String.valueOf(cipherSuitesToExclude));
      if (cipherSuitesToExclude != null && !cipherSuitesToExclude.isEmpty()) {
        secureConnector.setExcludeCipherSuites(cipherSuitesToExclude.toArray(new String[0]));
      }

azkaban/azkaban-webserver/src/package/conf/azkaban.properties

jetty.excludeCipherSuites=SSL_RSA_WITH_DES_CBC_SHA,SSL_DHE_RSA_WITH_DES_CBC_SHA,SSL_DHE_DSS_WITH_DES_CBC_SHA,SSL_RSA_EXPORT_WITH_RC4_40_MD5,SSL_RSA_EXPORT_WITH_DES40_CBC_SHA,SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA,SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA,SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_DSS_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_DSS_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_DSS_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_DSS_WITH_AES_128_CBC_SHA

**Comment by davidzchen** [comment]
Thanks for catching this. Can you open a Pull Request for this fix?

**Comment by nomorogbe** [comment]
Pull Request: https://github.com/azkaban/azkaban/pull/502

**Comment by bgdnlp** [comment]
+1 for this issue and the associated pull. Quick enough change, but would be nice to have it in main repo. Can confirm working.

**Comment by davidzchen** [comment]
Merged. Thanks for fixing this!
