### ISSUE TITLE
Email message send failed

### ISSUE THREAD

**Issue by zuopujun** [azkaban/azkaban#51]
com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. dk3sm36522188pbc.32 - gsmtp

```
at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2114)
at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1618)
at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
at azkaban.utils.EmailMessage.sendEmail(EmailMessage.java:170)
at azkaban.executor.ExecutorMailer.sendSuccessEmail(ExecutorMailer.java:167)
at azkaban.executor.ExecutorManager.finalizeFlows(ExecutorManager.java:725)
at azkaban.executor.ExecutorManager.access$1000(ExecutorManager.java:52)
```

my property followed:
# mail settings

mail.sender=...
# mail server to send job success/failure notifications to

mail.smtp.starttls.enable=true
mail.host=smtp.gmail.com
mail.user=...
mail.password=...
# mail.port=587

job.failure.email=...
job.success.email=zuopujun@gmail.com

The version is azkaban-2.1, and ssh turned on.
Did I set the properties wrong, looking forward to the answer.

**Comment by confessin** [comment]
Hello, I am getting same error, Do we have any way to fix this apart from changing the code?

**Comment by logiclord** [comment]
@confessin No even in latest version of Azkaban you will automatically set "mail." + protocol + ".auth" to be true (https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/utils/EmailMessage.java#L190)

**Comment by bgdnlp** [comment]
I don't know if mine is the same issue, but I'll fill in the details here.

I have localhost set as mail server. It doesn't use authentication, so mail.user and mail.password are not set. Local MTA is sendmail. When Azkaban is trying to send an email, /var/log/maillog has this message:
```
localhost [127.0.0.1] did not issue MAIL/EXPN/VRFY/ETRN during connection to MTA
```

I ran a tcpdump, Azkaban connects, issues EHLO, gets a response, then just closes the connection with no further communication.
