### ISSUE TITLE
Unable to run java jars against the hadoop cluster on EMR, only local

### ISSUE THREAD

**Issue by helena** [azkaban/azkaban#54]
This is probably not a bug or many others would have already reported it but I have hit the wall on what else to try.

I run this on the command line and it runs against the hadoop cluster as expected:

hadoop jar my.jar com.my.JobRunner com.my.Job --hdfs

Yet when I try all of these via azkaban here is what I get:
1. type=command
   command=hadoop jar my.jar com.my.JobRunner com.my.Job --hdfs
   -- runs, but not against the cluster, just local
2. type=javaprocess
   java.class= com.my.JobRunner
   main.args= com.my.Job --hdfs
   classpath=..the cp
   -- runs fine, but not against the cluster, just local
3. type=hadoopJava
   jobtype.classpath=...the cp
   main.args=com.my.Job --hdfs
   job.class=com.my.JobRunner.class 
   jobtype.class=azkaban.jobtype.HadoopJavaJob
   obtain.binary.token=true

Command: java -Xms1536m -Xmx1536m -XX:MaxPermSize=1638m -Xms64M -Xmx256M -cp /home/hadoop/project-jars/_:/home/hadoop/_:/home/hadoop/lib/_:/home/hadoop/azkaban-2.1/plugins/jobtypes/hadoopJava/azkaban-jobtype-2.1.jar:/home/hadoop/azkaban-2.1/lib/azkaban-2.1.jar:/home/hadoop/azkaban-2.1/plugins/jobtypes/hadoopJava/azkaban-hadoopsecuritymanager-2.1.jar:/home/hadoop/azkaban-2.1/plugins/jobtypes/hadoopJava/lib/_:/home/hadoop/_:/home/hadoop/lib/_ azkaban.jobtype.HadoopJavaJobRunnerMain com.my.Job --hdfs
12-10-2013 16:18:24 PDT my_job_name INFO - Environment variables: {JOB_NAME=my_job_name, JOB_PROP_FILE=/home/hadoop/azkaban-2.1/executions/16931/my_job_name/my_job_name_1392369104419033110_tmp, JOB_OUTPUT_PROP_FILE=/home/hadoop/azkaban-2.1/executions/16931/my_job_name/my_job_name_output_9031288206276976184_tmp}
12-10-2013 16:18:24 PDT my_job_name INFO - Working directory: /home/hadoop/azkaban-2.1/executions/16931/my_job_name
12-10-2013 16:18:25 PDT my_job_nameINFO - INFO Running job my_job_name
12-10-2013 16:18:25 PDT my_job_name INFO - INFO Class name com.my.JobRunner.class
12-10-2013 16:18:25 PDT my_job_name ERROR - Exception in thread "main" java.lang.ClassNotFoundException: com.my.JobRunner.class
12-10-2013 16:18:25 PDT my_job_name ERROR -     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at java.security.AccessController.doPrivileged(Native Method)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at azkaban.jobtype.HadoopJavaJobRunnerMain.getObject(HadoopJavaJobRunnerMain.java:299)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at azkaban.jobtype.HadoopJavaJobRunnerMain.<init>(HadoopJavaJobRunnerMain.java:146)
12-10-2013 16:18:25 PDT my_job_name ERROR -     at azkaban.jobtype.HadoopJavaJobRunnerMain.main(HadoopJavaJobRunnerMain.java:76)
12-10-2013 16:18:25 PDT my_job_name INFO - Process completed unsuccessfully in 0 seconds.
12-10-2013 16:18:25 PDT my_job_name ERROR - Job run failed!

Even if I copy my fat jar to the local dir for hadoopJava it still can't find it
jobtype.classpath=/home/hadoop/azkaban-2.1/plugins/jobtypes/hadoopJava/_,/home/hadoop/_,/home/hadoop/lib/*

I have had other issues as well with hadoopJava - and i'm hoping this will allow the jar to run against the cluster  but I don't understand why the command type using the hadoop command does not work, if it does when executing the jar directly vs via azkaban?

The docs are not clear as to what these should be:
job.class 
- is this the runner with a main method that the FQCN of the actual job class to run is passed to as a string arg? 
- is it the  FQCN or with .class after?
- what does this accomplish? jobtype.class=azkaban.jobtype.HadoopJavaJob

thanks

**Comment by elad** [comment]
I agree with @helena here, coming across the same problem, regardless of whether Hadoop is on EMR or not. Out of the box, Azkaban only works in local Hadoop mode... :/
