### ISSUE TITLE
How does the log4j.log.dir work?

### ISSUE THREAD

**Issue by Codefor** [azkaban/azkaban#556]
Hi,there!
in the first line of this file:
https://github.com/azkaban/azkaban/blob/master/azkaban-webserver/src/main/resources/log4j.properties

    log_dir=${log4j.log.dir}

How does the log4j.log.dir work?When I start the azkaban-webserver,I find it creates logs under / instead of the current working directory.

I tig the file log4j.properties and find that:

    2015-09-01 13:34 Hien Luu           o Rotate web and exec server log and remove unnecessary log statements #475

**Comment by hluu** [comment]
When starting up Azkaban server, you can add -Dlog4j.log.dir=<some path> to
tell log4j where to place the log file.

**Comment by Codefor** [comment]
Thx.
I've contributed a patch ,setting default log_dir to $AZKABAN_DIR/logs
https://github.com/azkaban/azkaban/pull/557
