### ISSUE TITLE
Kill command in azkaban doesn't kill a command job that starts another program

### ISSUE THREAD

**Issue by vikramkone** [azkaban/azkaban#571]
Hi,
I have a simple job that looks like this
#myjob.job
type=command
command=spark-submit --class org.myclass myap.jar

As you can see, this command executes the spark-submit command to submit a spark job.
When I press kill in the portal, Azkaban says that the flow is killed, but I still see the spark job running in the spark maser UI.

Is this a bug in azkaban or by design? Can azkaban kill processes that are spawned from command job type reliably? or is this not supported?

@hluu  @davidzchen  Any thoughts?

**Comment by vikramkone** [comment]
I figured this out. Turns our that when I use "dse spark-submit..." as the command to be executed then there is a child process that gets spawned by dse. When I press kill in the azkaban portal only the parent process is killed and not the child process and hence I see it still running in spark ui.

Solution was to wrap the command in a shell script and use a trap function that kills the child process upon receiving SIGINT/SIGTERM

**Comment by mixalturek** [comment]
It's much simpler to execute it as "exec spark-submit", which replaces the shell without creating a new process. I didn't try to put it directly to "command=" but it nicely works in spark-submit wrapper script.

**Comment by afsaar** [comment]
i am running spark job from Azkaban by calling shell script consists of spark submit command. I can spark job is completed and nothing remains in spark side ,still Azkaban is showing job as running and it does not stop .any suggestions?
