### ISSUE TITLE
Azkaban 3.0 solo server not working

### ISSUE THREAD

**Issue by vikramkone** [azkaban/azkaban#575]
Seeing this error in the 3.0 solo server version when executing a simple command in the job of type "command"

2-11-2015 13:14:25 PST Ping INFO - Starting job Ping at 1448226865432
22-11-2015 13:14:25 PST Ping INFO - azkaban.webserver.url property was not set
22-11-2015 13:14:25 PST Ping INFO - job JVM args: -Dazkaban.flowid=Ping -Dazkaban.execid=3 -Dazkaban.jobid=Ping
22-11-2015 13:14:25 PST Ping INFO - Building command job executor. 
22-11-2015 13:14:25 PST Ping ERROR - Failed to build job executor for job Pingnull
22-11-2015 13:14:25 PST Ping ERROR - Failed to build job type
azkaban.jobtype.JobTypeManagerException: Failed to build job executor for job Ping
    at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:371)
    at azkaban.execapp.JobRunner.prepareJob(JobRunner.java:520)
    at azkaban.execapp.JobRunner.run(JobRunner.java:439)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at azkaban.utils.Utils.getTypes(Utils.java:263)
    at azkaban.utils.Utils.callConstructor(Utils.java:268)
    at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:366)
    ... 7 more
22-11-2015 13:14:25 PST Ping ERROR - Job run failed preparing the job.
22-11-2015 13:14:25 PST Ping INFO - Finishing job Ping attempt: 0 at 1448226865442 with status FAILED
22-11-2015 13:14:25 PST Ping INFO - No job callbacks for status: FAILURE
22-11-2015 13:14:25 PST Ping INFO - No job callbacks for status: COMPLETED

**Comment by logiclord** [comment]
Hi vikramkone, can you please confirm your version of azkaban-plugins ?

**Comment by jeroenvlek** [comment]
I'm having the same NPE and I don't have azkaban-plugins installed. Does this mean that you do need azkaban-plugins? Even for a simple command type job?

**Comment by jeroenvlek** [comment]
What puzzles me is that the NPE is caused by one of the args in the following being null:

```
  public static Class<?>[] getTypes(Object... args) {
    Class<?>[] argTypes = new Class<?>[args.length];
    for (int i = 0; i < argTypes.length; i++)
      argTypes[i] = args[i].getClass();
    return argTypes;
  }

  public static Object callConstructor(Class<?> c, Object... args) {
    return callConstructor(c, getTypes(args), args);
  }
```

Looking at the caller:

```
Utils.callConstructor(executorClass, jobId, pluginLoadProps,
              jobProps, logger);
```

This means that jobId, pluginLoadProps, jobProps or logger should be null. 

jobId evaluates to 'command' and is logged via logger in the handling of the NPE, thus these both are not null.

pluginLoadProps is initialized in that same method and can't be null. That leaves jobProps. A bit lower in the stack, in `prepareJob()` there is a null check, but the member isn't final, so is it possible that it's set to null as caused by a race condition?

**Comment by todd-fritz** [comment]
I am receiving the same error when attempting to run a command job type in distributed mode.  My understanding is that the job plugin additions are not needed for the default job types.  

Could someone please respond to this issue?

Within class:  JobTypeManager

private void loadDefaultTypes(JobTypePluginSet plugins) throws JobTypeManagerException {
  logger.info("Loading plugin default job types");
  plugins.addPluginClass("command", ProcessJob.class);
  plugins.addPluginClass("javaprocess", JavaProcessJob.class);
  plugins.addPluginClass("noop", NoopJob.class);
  plugins.addPluginClass("python", PythonJob.class);
  plugins.addPluginClass("ruby", RubyJob.class);
  plugins.addPluginClass("script", ScriptJob.class);
}

**Comment by todd-fritz** [comment]
I was able to work around the problem by adding defensive code (after reviewing the git history of changes).  Try after adding this code to JobTypeManager after line 364, immediately before the job is populated.
```java      
      if (pluginLoadProps == null) {
        logger.info("...pluginLoadProps was null, assigning new empty Props().");
        pluginLoadProps = new Props();
      }
      if (pluginJobProps == null) {
        logger.info("...pluginJobProps was null, assigning new empty Props().");
        pluginJobProps = new Props();
      }
```

**Comment by vikramkone** [comment]
Gaurav I'm not using any plugins. Only the default command job type

#v




On Thu, Dec 3, 2015 at 3:21 PM -0800, "Todd Fritz" <notifications@github.com> wrote:












I was able to work around the problem by adding defensive code (after reviewing the git history of changes).  Try after adding this code to JobTypeManager after line 364, immediately before the job is populated.

      if (pluginLoadProps == null) {
        logger.info("...pluginLoadProps was null, assigning new empty Props().");
        pluginLoadProps = new Props();
      }
      if (pluginJobProps == null) {
        logger.info("...pluginJobProps was null, assigning new empty Props().");
        pluginJobProps = new Props();
      }

**Comment by juhoautio** [comment]
I encountered the same problem.

Thanks @todd-fritz: setting `pluginJobProps` to a non-null value helps.

If you look at `JobTypeManager` you'll find out that `pluginJobProps` isn't even used after that line any more, so that piece of code is redundant.

--

P.S. I couldn't get these log messages to be shown anywhere..? I was able to verify with `System.err.println` that this additional code is executed, though.

There's just `logs/azkaban-execserver.log` that is being populated with some logs, but only this line from the `JobTypeManager`:
```
2015/12/07 13:05:36.138 +0200 INFO [JobTypeManager] [Azkaban] Loading plugin default job types.
```
Maybe the logging system somehow gets misconfigured after that line is printed?

**Comment by vikramkone** [comment]
Is someone going to do a pull request to fix the issue ? Seems like a DOA
bug for 3.0 solo server

**Comment by juhoautio** [comment]
I could do a PR like that to at least fix job running, but I wonder if a proper fix would require something more? I mean why does it get set to null in the first place – maybe that's wrong and should be looked at. I wouldn't know – just getting started with Azkaban.

**Comment by jeroenvlek** [comment]
```
   Props pluginLoadProps = pluginSet.getPluginLoaderProps(jobType);
      if (pluginLoadProps != null) {
        pluginLoadProps = PropsUtils.resolveProps(pluginLoadProps);
      } else {
        // pluginSet.getCommonPluginLoadProps() will return null if there is no plugins directory.
        // hence assigning default Props() if that's the case
        pluginLoadProps = pluginSet.getCommonPluginLoadProps();
        if(pluginJobProps == null)
          pluginJobProps = new Props();
      }
```

I don't understand: How can this code make pluginLoadProps null?

**Comment by jeroenvlek** [comment]
@juhoautio Do you want to create the PR? I don't deserve it after that display of sloppy reading ;)

**Comment by juhoautio** [comment]
@jeroenvlek true, that makes sense. Please submit the fix by all means!

**Comment by jeroenvlek** [comment]
PR here: https://github.com/azkaban/azkaban/pull/585

**Comment by logiclord** [comment]
Apologies for delayed response.  

This is a know issue we encountered while releasing Azkaban 3.0. Somehow it's fix fell through the cracks. We observe this issue  if we have no Azkaban plugins and hence common.properties from plugin directory is NULL.

Thanks @jeroenvlek  for the fix.

**Comment by ameyamk** [comment]
This is working. Please re-open if you encounter issues.
