### ISSUE TITLE
Does Azkaban support for job scheduler on Spark ?

### ISSUE THREAD

**Issue by MarsXDM** [azkaban/azkaban#600]
As the subject.
I want to realize ETL on Spark using scala. 
Does Azkaban support for job scheduler on Spark ?

**Comment by vikramkone** [comment]
Yes it does. There is a spark job type plugin that you can use to submit spark jobs internally via spark-submit command.
Alternatively you can also use the command job type and call spark-submit command in your job config

**Comment by yannli** [comment]
so what is the difference between these two modes. 
refer:
http://stackoverflow.com/questions/37290368/how-azkaban-run-spark-job-calling-spark-task-type-command-by-the-shell-and-b

**Comment by r7raul1984** [comment]
@vikramkone   what is the difference between these two modes？

**Comment by MarsXDM** [comment]
Thanks .

**Comment by MarsXDM** [comment]
Thanks
