### ISSUE TITLE
How to set SLA for a flow using ajax api

### ISSUE THREAD

**Issue by vikramkone** [azkaban/azkaban#603]
I tried this and it didn't work.. What am I doing wrong? There is no documentation for this api so this is based on code inspection of schedule servlet class.

`
curl -k https://HOST:PORT/schedule -d "ajax=setSla&scheduleId=2&slaEmails=foo@bar.com&settings=,06:00,SUCCESS,true,true" -b azkaban.browser.session.id=SESSION_ID`

**Comment by vikramkone** [comment]
Figured this out by looking at the code..need to do this

` curl -k https://HOST:PORT/schedule -d "ajax=setSla&scheduleId=2&slaEmails=foo@bar.com&settings[0]=,06:00,SUCCESS,true,true" -b azkaban.browser.session.id=SESSION_ID`

**Comment by moscovig** [comment]
It's not working
