### ISSUE TITLE
The job do not work on Multiple Executor Mode

### ISSUE THREAD

**Issue by neilyooloil** [azkaban/azkaban#610]
Hi guys:
  I am new on azkaban. 
  I builded azkaban 3.0 from Source .  And I tried to run the command type job on Multiple Executor Mode.  But the job's Status is always Preparing.  It does not run .There is no Exception .The webServer logs like this:

INFO [ExecutorManager] [Azkaban] Reached handleNoExecutorSelectedCase stage for exec 10 with error count 0 

My operation reference the 3.0 document.
I do not know how to do now . Please help me . Thank u!

**Comment by younseunghyun** [comment]
Have you set a ip of executor's at db and invoke it?

**Comment by neilyooloil** [comment]
yes , i set the host port, active =1 at db .
and I set this in azkaban.properties
azkaban.use.multiple.executors=true
azkaban.executorselector.filters=StaticRemainingFlowSize,MinimumFreeMemory,CpuStatus
azkaban.executorselector.comparator.NumberOfAssignedFlowComparator=1
azkaban.executorselector.comparator.Memory=1
azkaban.executorselector.comparator.LastDispatched=1
azkaban.executorselector.comparator.CpuUsage=1
 I thought I just need set the db and the properties .  But how l can invoke it? 
thank u!

**Comment by younseunghyun** [comment]
you have to invoke, u set the executor setting on azkabn webserver.

there is two method to invoke.

1) restart
2) api 

api is not in the documents.

To invoke, using this kinds of script
plz modify azkaban url and id, password
AZKABAN_URL=**URLOfYourAzkaban**

SESSION_ID=$(curl -s -k -X POST --data 'action=login&username=**ID**&password=**PASSWORD**' $AZKABAN_URL | jq '."session.id"')

SESSION_ID=$(echo $SESSION_ID | sed 's/"//g')

echo "SESSINO_ID :" $SESSION_ID

curl -s -X POST --data "session.id=$SESSION_ID&ajax=reloadExecutors" $AZKABAN_URL/executor

**Comment by neilyooloil** [comment]
thank u so much!  nice to meet u!

**Comment by younseunghyun** [comment]
i hope it can help you.

i struggle with this issue for a week ...

**Comment by neilyooloil** [comment]
The webserver logs shows:
 INFO [ExecutorManager] [Azkaban] Successfully refreshed executor: 192.168.56.201:12321 (id: 3) with executor info : {
  "remainingMemoryPercent" : 84.9490145958216,
  "remainingMemoryInMB" : 846,
  "remainingFlowCapacity" : 30,
  "numberOfAssignedFlows" : 0,
  "lastDispatchedTime" : 0,
  "cpuUsage" : 0.0
}
INFO [ExecutorManager] [Azkaban] Successfully refreshed executor: 192.168.56.202:12321 (id: 4) with executor info : {
  "remainingMemoryPercent" : 85.03095192356697,
  "remainingMemoryInMB" : 847,
  "remainingFlowCapacity" : 30,
  "numberOfAssignedFlows" : 0,
  "lastDispatchedTime" : 0,
  "cpuUsage" : 0.0
}
 INFO [ExecutorManager] [Azkaban] Using dispatcher for execution id :11
 INFO [ExecutorManager] [Azkaban] Reached handleNoExecutorSelectedCase stage for exec 11 with error count 0
INFO [ExecutorManager] [Azkaban] Using dispatcher for execution id :11
 INFO [ExecutorManager] [Azkaban] Reached handleNoExecutorSelectedCase stage for exec 11 with error count 0

The web server have recognized executors.

But the jobs's status is still Preparing. It does not run....

I have  restarted before. 


Did u meet the issue?

**Comment by younseunghyun** [comment]
Ah.. delete the MinimumFreeMemory of filter. it check memory of executor and if memory is under 4GB, then return false.

**Comment by neilyooloil** [comment]
Thank u!
I delete the MinimumFreeMemory of filter. It has another exception......
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:162)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:325)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.readLine(BufferedReader.java:317)
        at java.io.BufferedReader.readLine(BufferedReader.java:382)
        at azkaban.utils.FileIOUtils$NullLogger.run(FileIOUtils.java:178)
Uploading flowId step1
Uploading flowId step1

Do u know how to fix it .... thanks...

**Comment by younseunghyun** [comment]
I'm encountered that kinds of error, but project worked.

Project flow isn't executed?

**Comment by neilyooloil** [comment]
It failed . Here is the exception...
19-02-2016 11:08:05 CST step5 INFO - Starting job step5 at 1455851285516
19-02-2016 11:08:05 CST step5 INFO - azkaban.webserver.url property was not set
19-02-2016 11:08:05 CST step5 INFO - job JVM args: -Dazkaban.flowid=step1 -Dazkaban.execid=17 -Dazkaban.jobid=step5
19-02-2016 11:08:05 CST step5 INFO - Building command job executor. 
19-02-2016 11:08:05 CST step5 ERROR - Failed to build job executor for job step5null
19-02-2016 11:08:05 CST step5 ERROR - Failed to build job type
azkaban.jobtype.JobTypeManagerException: Failed to build job executor for job step5
	at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:371)
	at azkaban.execapp.JobRunner.prepareJob(JobRunner.java:520)
	at azkaban.execapp.JobRunner.run(JobRunner.java:439)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
	at azkaban.utils.Utils.getTypes(Utils.java:263)
	at azkaban.utils.Utils.callConstructor(Utils.java:268)
	at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:366)
	... 7 more
19-02-2016 11:08:05 CST step5 ERROR - Job run failed preparing the job.
19-02-2016 11:08:05 CST step5 INFO - Finishing job step5 attempt: 0 at 1455851285690 with status FAILED

It shows "azkaban.webserver.url property was not set" . But I did not see the property in properties...

**Comment by neilyooloil** [comment]
I found the exception....
java.lang.Exception: Cannot request memory (Xms 0 kb, Xmx 0 kb) from system for job step5
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:86)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:590)
	at azkaban.execapp.JobRunner.run(JobRunner.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
19-02-2016 11:36:56 CST step5 ERROR - Cannot request memory (Xms 0 kb, Xmx 0 kb) from system for job step5 cause: null
19-02-2016 11:36:56 CST step5 INFO - Finishing job step5 attempt: 0 at 1455853016337 with status FAILED

**Comment by younseunghyun** [comment]
Well I haven't encountered this kinds of error ...

**Comment by younseunghyun** [comment]
Above issue is due to memory contraint of azkaban.

Default executor setting need minimum free memory size to be over 3GB. To turn off the this property, put this property at plugins/jobtypes/commonprivate.properties at executor server

`memCheck.enabled=false`

**Comment by vblvbl** [comment]
azkaban requires that you configure the Network Time Protocol (NTP) service on each machine in your cluster

**Comment by lizhenhuan** [comment]
I have that problem too.That is because exec server time is behind web server in mill seconds.
When you click execute button on azkaban web page, web server will callExecutorServer and send an execute action to executor server by restful api. Executor server will start running this job and update execution_flows table to running status.  
There is an thread in ExecutorManager class named QueueProcessorThread. This thread will check job status by send update request to executor server. Executor server will check the job updateTime from web server and updateTime from executor server. If the web server's updateTime is big than executor server's updateTime. Executor Server will ignore this update request and send no update data back to web server. And then web server will never update this job status from preparing to running.
I this you can setup  Network Time Protocol (NTP) service on each machine in your cluster as @vblvbl  said or modify FlowRunner.updateFlow() method from "updateFlow(System.currentTimeMillis())" to updateFlow(System.currentTimeMillis() + 1000);

**Comment by younseunghyun** [comment]
why network time protocol issue is written here? any relation with title?

**Comment by lizhenhuan** [comment]
If the web server's updateTime is big than executor server's updateTime. Executor Server will ignore this update request and send no update data back to web server. 
This web server's updateTime is System.currentTimeMills() in web server.
This executor server's updateTime is System.currentTimeMills() in executor server.
If there is no NTP it may has small time difference and web server is big than executor server, executor server will ignore web server's update request .
NTP service will keep web server's System.currentTimeMills() equals executor server's System.currentTimeMills()
