### ISSUE TITLE
"alert.type" property

### ISSUE THREAD

**Issue by kddeisz** [azkaban/azkaban#617]
Is there a way to set this property globally and have it apply to every flow? At the moment the only way I can figure out to set this property is through the override properties in the interface, and I'd much rather just set it in the job file or globally for all jobs.

**Comment by kddeisz** [comment]
@logiclord Tagging you because it seems like you're the only one contributing to this anymore.

Is the above thing an issue or am I doing something wrong? Happy to work on it if it's an issue.

**Comment by logiclord** [comment]
@kddeisz You are right. alert.type is part of flow properties section, which can only be specified overriide properties interface. We do have a backlog item to specify flow properties as part of zip project like .job properties file. Feel free to contribute on this

**Comment by kddeisz** [comment]
Thanks @logiclord, is there already an existing issue? Otherwise I'll just reference this one in the future

**Comment by logiclord** [comment]
I tried searching older ticket but couldn't find it. Feel free to propose something for this and refer this issue.

**Comment by antey86** [comment]
https://github.com/azkaban/azkaban/pull/1727
