### ISSUE TITLE
FETCH_ACTIVE_EXECUTABLE_FLOW  is wrong   in web-server 

### ISSUE THREAD

**Issue by superwood** [azkaban/azkaban#621]
JdbcExecutorLoader.java    

line 1333

      "SELECT ex.exec_id exec_id, ex.enc_type enc_type, ex.flow_data flow_data, et.host host, "
        + "et.port port, ax.update_time axUpdateTime, et.id executorId, et.active executorStatus" 
        + " FROM execution_flows ex"
        + " INNER JOIN "
        + " active_executing_flows ax ON ex.exec_id = ax.exec_id"
        + " INNER JOIN "
        + " executors et ON ex.executor_id = et.id";   //  ==> ex.executor_id may be ex.exec_id 
line 
         private static String FETCH_QUEUED_EXECUTABLE_FLOW =
      "SELECT ex.exec_id exec_id, ex.enc_type enc_type, ex.flow_data flow_data, "
        + " ax.update_time axUpdateTime FROM execution_flows ex"
        + " INNER JOIN"
        + " active_executing_flows ax ON ex.exec_id = ax.exec_id"
        + " Where ex.executor_id  is  NULL";     //  ===> the same .

JdbcExecutorLoader.java    line   1009

"UPDATE execution_flows SET executor_id=? where exec_id=?"

Or

the table execution_flows  create by  create-all-sql-3.0.0.sql  is wrong 。 table execution_flows  has no  executor_id   field. 
 17 CREATE TABLE execution_flows (
 18     exec_id INT NOT NULL AUTO_INCREMENT,
 19     project_id INT NOT NULL,
 20     version INT NOT NULL,
 21     flow_id VARCHAR(128) NOT NULL,
 22     status TINYINT,
 23     submit_user VARCHAR(64),
 24     submit_time BIGINT,
 25     update_time BIGINT,
 26     start_time BIGINT,
 27     end_time BIGINT,
 28     enc_type TINYINT,
 29     flow_data LONGBLOB,
 30     PRIMARY KEY (exec_id)
 31 );

version
3.0.0
89a99d3ddf1ad10635bf55fa33791e6c990acda4
https://github.com/azkaban/azkaban.git

**Comment by fsi206914** [comment]
Duplicated issues
