### ISSUE TITLE
How to migrate  an project from one azkaban to another with it's  schduler, notice and other flow properties?  

### ISSUE THREAD

**Issue by superwood** [azkaban/azkaban#626]
How to migrate  an project from one azkaban to another with it's  schduler, notice and other flow properties?

**Comment by younseunghyun** [comment]
Information of project is stored in db. So, you just have to migrate data at db to other

**Comment by ameyamk** [comment]
Unfortunately not available as a feature.

Hopefully you do not have to do this with #670 in progress.
