### ISSUE TITLE
Is Azkaban 3.0 on github stable setup ?

### ISSUE THREAD

**Issue by sathedeepashree** [azkaban/azkaban#627]
Hi,
I checked Azkaban 3.0 documentation at http://azkaban.github.io/azkaban/docs/latest/, but corresponding updated code repository is not available at downloads page http://azkaban.github.io/downloads.html.

But i found one on github at https://github.com/azkaban/azkaban, The issue I am facing is this repository is inconsistent. I faced problems with SQL queries resulting in column not found error [e.g. executor_id was used instead of exec_id in select query with table execution_flows]

Can you please let me know, if 3.0 is the stable version to use for multiple executor support ? and also give link to the stable code.

Thanks.
Deepashree.

**Comment by devangorder** [comment]
I ran into this issue recently too. After building 3.0 from the latest code in the repo, I had to run azkaban-sql-3.0.0/update.active_executing_flows.3.0.sql and azkaban-sql-3.0.0/update.execution_flows.3.0.sql after azkaban-sql-3.0.0/create-all-sql-3.0.0.sql to sort out the sql errors. It seems the create-all sql file is not entirely all-encompassing from scratch.

**Comment by superwood** [comment]
The right create-all-sql**.sh  in   version release-3.0   is create-all-sql-2.2.sql . 
The  create-all-sql-3.0.0.sql  is not for release-3.0  . 

See my issue 
      FETCH_ACTIVE_EXECUTABLE_FLOW is wrong in web-server #621
     https://github.com/azkaban/azkaban/issues/621

**Comment by ameyamk** [comment]
we are in prod with 3.19 - and is a stable release

**Comment by JabbaTheCoder** [comment]
The issue was caused by a defect in the LDAP plugin, not Azkaban itself. I have fixed the issue with the plugin, contributed it, and it was accepted. We have enough running Azkaban in production since then without any I'll effects. Basically, if you are using LDAP plugin for authentication, make sure to get the latest version and you will be fine.
