### ISSUE TITLE
Multiple Hadoop cluster support

### ISSUE THREAD

**Issue by BrianGallew** [azkaban/azkaban#640]
Given the multiple-executor support already available, I think it would be wonderful if flows could be assigned to specific executors (both scheduled and ad-hoc).  This would allow having one Azkaban managing multiple Hadoop clusters.  For my purposes, that would enable staged Hadoop cluster migration.

**Comment by BrianGallew** [comment]
I'd have tagged this Enhancement, but that's not available.

**Comment by ameyamk** [comment]
This is possible with work being done on #670
