### ISSUE TITLE
Is  Multiple Executor Mode ready  with "release-3.0" version ?

### ISSUE THREAD

**Issue by superwood** [azkaban/azkaban#642]
http://azkaban.github.io/azkaban/docs/latest/#multipleExecutors-config

The document says  must "insert into executors(host,port) values("EXECUTOR_PORT",EXECUTOR_PORT);"     .   But there are no ''executors" table created by azkaban-sql-scripts  .     I grep  "executors" from all the source code   and  find nothing .  Then I grep  "azkaban.use.multiple.executors"  , "multiple.executors"   or "executors"  from source code  and find nothing too. 

How to create table name "executors", ? And the "executors" table is used ?

**Comment by tsingker88** [comment]
hello, friend. I had the same problem. Now, I know that only the 3.0 version support Multiple Executor Mode, but the corresponding package has not been released. So let us just wait....
I hope this can be helpful for you, though I cannot help you solve the problem.

**Comment by sumpan** [comment]
try to use tags 3.0.0 
"excutors"  table is needed in mysql

**Comment by fsi206914** [comment]
I believe 3.0 azkaban-sql folder has all necessary tables now. Please check it out.
