### ISSUE TITLE
The scheduler  does not work   with  "release-3.0" version . Is "release-3.0" is stable?

### ISSUE THREAD

**Issue by superwood** [azkaban/azkaban#643]
The scheduler  does not work   with  "release-3.0" version . Is "release-3.0" is stable?

I schedule one workflow  "demo" and the  time repeates  is 5 minutes.  But no thing happens   5 minutes passed, and 10 minutes passed too .

Is "release-3.0" is stable? 

ID Flow Project Submitted By First Scheduled to Run Next Execution Time Repeats Every HasSLA
3   end demo    azkaban 2016-04-19 19:36:00 2016-04-19 19:36:00 5 minute(s) false

**Comment by ameyamk** [comment]
yes. we are now on 3.19
