### ISSUE TITLE
SlaAlertAction Error

### ISSUE THREAD

**Issue by vvii** [azkaban/azkaban#668]
While trigglered Sla on a scheduled flow, I got an error message in azkaban-webserver.log
![qq20160616-1](https://cloud.githubusercontent.com/assets/1711944/16107284/060de946-33ce-11e6-8d81-34cdc2798913.png)

and I found the public method **sendSlaAlertEmail** in file azkaban-common/src/main/java/azkaban/utils/Emailer.java
doesn't call 

> message.setTLS(tls);

this would lead to above exception.

**Comment by juhoautio** [comment]
Candidate fix: https://github.com/azkaban/azkaban/pull/673

**Comment by juhoautio** [comment]
Fix was merged, this issue could be closed/resolved.

**Comment by fsi206914** [comment]
#673 fixed. Thank you guys.
