### ISSUE TITLE
Which MySQL version should I use with Azkaban 3.0?

### ISSUE THREAD

**Issue by devangorder** [azkaban/azkaban#671]
What is the suggested version of MySQL to use with Azkaban 3.0? I am currently running it with Version 5.7.4 which I already had installed on this server from running Azkaban 2.6.4 and it seems to be working fine, but I am looking into upgrading MySQL for security reasons seeing as the latest release is now 5.7.13. I was wondering what's the latest release of MySQL anyone has tested with Azkaban 3.0?

**Comment by fsi206914** [comment]
Hi @devangorder , we haven't tested the compatibility. Thanks for raising this point. Would you mind testing this if you have time? and pull request some documentation supplement?

**Comment by devangorder** [comment]
I've been running my Azkaban installation off the latest version of MySQL (5.7.13) for a few weeks now and haven't ran into any issues yet. We haven't done enough extensive testing to determine its full compatibility, but I don't expect to run into any issues.

**Comment by fsi206914** [comment]
Nice! Thanks @devangorder for your update.
