### ISSUE TITLE
Job logs missing while killing

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#684]
When a job is killed, the job log goes blank in the web UI (JobDetails).

This is the case until the jobtype (java class) execution actually exits.

After that the job log appears again.
## 

It's also confusing that a job is shown as KILLED immediately, even if the job thread hasn't exited. Having a state transition RUNNING->KILLING->KILLED would clarify this greatly.

**Comment by ismailsimsek** [comment]
currently having same issue  +1

**Comment by juhoautio** [comment]
Looks like this PR https://github.com/azkaban/azkaban/pull/1172 (currently not merged yet) fixes the missing logs problem as a "side-effect".

**Comment by juhoautio** [comment]
Let's keeping this open though: I'm pretty sure that in case of an interrupted execution (azkaban-executor stopped in the middle of an execution), logs are still being overwritten with an empty value.

**Comment by juhoautio** [comment]
This one is fixed, created another one for the executor restart scenario: https://github.com/azkaban/azkaban/issues/1527
