### ISSUE TITLE
Autogenerated version / commit info with artifacts

### ISSUE THREAD

**Issue by suvodeep-pyne** [azkaban/azkaban#695]
Currently, version numbers are manually managed in gradle.properties file. This is inconvenient and quickly falls out of date with more commits.

It would be good to move to a automated versioning and use git tags to annotate releases.
for eg. azkaban-web-server-2.7.0-474-gbc0be80.zip instead of azkaban-web-server-3.0.0.zip

Also, a single large gradle script for all projects is difficult to manage. It would be good to have a build script for each subproject.

**Comment by logiclord** [comment]
+1
It will be helpful in tracking bits version in production. This will be a good change to have.

**Comment by suvodeep-pyne** [comment]
@logiclord : Thanks Gaurav! This has been merged already into master.

Closing this issue.
