### ISSUE TITLE
azkaban3.0 schedule flow bug

### ISSUE THREAD

**Issue by hitwangyu** [azkaban/azkaban#701]
When I use azkaban3.0 and shedule a flow, I find a bug. The bug is as follow.
First shedule a flow with recurring period  1d.  Then I reSchedule the flow with recurring period 1h.
Then I restart webServer and I find the flow's period recover to 1d.
So I read azkaban source code and I find the cause is that updating table triggers is at the time when the flow is triggered to run. So if you change the schedule config and restart webserver before the flow's nextExecutionTime, the schedule config will recover to the old.

**Comment by fsi206914** [comment]
Hi @hitwangyu , thanks for reporting this bug!! You are correct. The azkaban server seems not updating new Trigger to DB immediately when the schedule changes. I'll look into this later.

**Comment by fsi206914** [comment]
Can be closed due to #708
