### ISSUE TITLE
How can I use http job callback in web&executor mode?

### ISSUE THREAD

**Issue by xFaris** [azkaban/azkaban#748]
I modify azkaban-web-2.5.0/conf/azkaban.properties like this, but it doesn`t work

job.notification.started.1.url=http://abc.com/api/v1/resource
job.notification.started.1.method=POST
job.notification.started.1.body={"type":"workflow", "source":"Azkaban", "content":"{server}:?{project}:?{flow}:?{executionId}:?{job}:?{status}"}
job.notification.started.1.headers=Content-type:application/json

**Comment by fsi206914** [comment]
Maybe I'm wrong, but this configurations should be inside one job I believe.

**Comment by xFaris** [comment]
help！

**Comment by devangorder** [comment]
I never got this to work either, by putting the values inside azkaban.properties. Not sure if they should go in the job file definitions, or if this functionality doesn't work as a whole.

**Comment by fsi206914** [comment]
@xFaris Have you tried putting these configurations to job files?

**Comment by kanhaiyaagarwal** [comment]
any solution here ?

**Comment by Codefor** [comment]
putting these configurations to job files works!

**Comment by fsi206914** [comment]
Closing this issue as @Codefor confirmed.
