### ISSUE TITLE
Directories created during azkaban-web-server:build

### ISSUE THREAD

**Issue by suvodeep-pyne** [azkaban/azkaban#754]
It seems that there are some directories which are being created when trying to build azkaban-web-server.

- azkaban-web-server/bower
- azkaban-web-server/node_modules
- azkaban-web-server/bower_components/
- azkaban-web-server/velocity.log

If these are temporary directories then can these be moved inside the build directory so that they are cleaned up automatically.

**Comment by suvodeep-pyne** [comment]
@fsi206914 I think you are more familiar with these components. Let me know your thoughts.

**Comment by fsi206914** [comment]
+1. Let's move these to build folder to keep web root folder clear.

**Comment by fsi206914** [comment]
@suvodeep-pyne I will fix this by checking in JsTest conponent.

**Comment by hreview** [comment]
awesome. let me know if you need any help with gradle.

**Comment by fsi206914** [comment]
@hreview Not sure how to do this work? we should move these files after :build, right? I noticed that :build and :distTar is two different tasks? Then how could we handle this?

**Comment by suvodeep-pyne** [comment]
I see. Let's talk about it tomorrow. btw @hreview is me in the above comment.

**Comment by fsi206914** [comment]
#756 resolved this issue.
