### ISSUE TITLE
Azkaban 2.7 to 3.0 Upgradation Suggestion 

### ISSUE THREAD

**Issue by rajivchodisetti** [azkaban/azkaban#781]
HI , 

Can some one please let me know what all precautions need to be taken while upgrading Azkaban from 2.7 to 3.0 . 

There are some DDL changes and also change in gradle version which will result in change in folder structure  and do i need to re-upload all the projects again or is there any hack and what other precautions need to be taken so that there is less downtime

**Comment by fsi206914** [comment]
No need to re-upload all the projects.
http://azkaban.github.io/azkaban/docs/latest/
Change configurations, which is described Multiple Executor Mode section. Also, you need to change DB schema which is also in document.

Why not try deploy the latest code on you local machine.
