### ISSUE TITLE
Release file "azkaban-solo-server-3.1.0.tar.gz" contains duplicate libraries

### ISSUE THREAD

**Issue by pashazm** [azkaban/azkaban#784]
On release downloads page
[https://github.com/azkaban/azkaban/releases](https://github.com/azkaban/azkaban/releases) 	
Release file "azkaban-solo-server-3.1.0.tar.gz" contains duplicate libraries in "lib" directory:

- azkaban-common-2.7.0-479-ge94d5a3.jar

- azkaban-common-3.1.0.jar 

The same for other "azkaban-.." jars.
Similar in "azkaban-exec-server-3.1.0.tar.gz", maybe, other archives.

If build project from sources, all fine, no duplicates.

**Comment by HappyRay** [comment]
Thanks for reporting this. 

Removed the binaries that have issues.
