### ISSUE TITLE
proxy bug lets everyone run jobs as anyone

### ISSUE THREAD

**Issue by shadyxu** [azkaban/azkaban#785]
I am using Azkaban 3.2.0 and has set "Execute-As-User" as the documentations says. Then every job is run as the user who submits it. That's good and as expected.

However I found that I can run as any user if I set the property "user.to.proxy" by the "Flow Parameters" tab on the web before submitting the flow.

BTW, I was running command jobs and I didn't set any proxy users in azkaban-users.xml.

**Comment by wangqiaoshi** [comment]
can We configure a parameter in azkaban.properties file?
eg
execute.as.user.bySystem=true
if true,we can not set property "user.to.proxy".

**Comment by HappyRay** [comment]
Did you restrict the proxy user list?
From the doc http://azkaban.github.io/azkaban/docs/latest/
"If proxy users are turned on, proxy users allows the project workflows to run as those users. This is useful for locking down which headless accounts jobs can proxy to. They are removed by clicking on the 'Remove' button once added.
"
Did you login as an admin?
