### ISSUE TITLE
Extend ProjectValidator interface to validate on additional metadata other than Project object

### ISSUE THREAD

**Issue by pranayhasan** [azkaban/azkaban#787]
Context: [`Pull Request`](https://github.com/azkaban/azkaban/pull/782)

`public interface ProjectValidator {`
`    boolean initialize(Props configuration);`
`    String getValidatorName();`
`    ValidationReport validateProject(Project project, File projectDir);`
`}`

The idea of creating a more generic validator is to extend the ProjectValidator to not only pass on Project object as in [validateProject](https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/project/validator/ProjectValidator.java#L37) method, but also a metadata object (mostly contains key-value pairs). This helps in not only validating a project based on fields in Project class but also transient fields and on other metadata which gets uploaded with the Zip. 

We need this interface for Validating zip metadata and thereby reject zips in the future. We can't change the existing ProjectValidator to include this metadata in [validateProject](https://github.com/azkaban/azkaban/blob/master/azkaban-common/src/main/java/azkaban/project/validator/ProjectValidator.java#L37) method as it is not backward compatible and hence have to extend existing ProjectValidator.

`public interface MetadataValidator extends ProjectValidator {`
_`@Override`_
`  ValidationReport validateProject(Project project, File projectDir, Metadata metadata);`
`}`

**Comment by suvodeep-pyne** [comment]
@HappyRay Does it make sense to rename our original ProjectValidator to simply Validator ? I think the only plugin using this interface is the byte-ray plugin. It might be good to make that a generic class rather than have individual validator interfaces of different kinds.

What other kinds of validators can we think of ?

**Comment by pranayhasan** [comment]
@suvodeep-pyne I wonder if we can refactor an interface, as it breaks all implementations of ProjectValidator interface, if there are any outside Linkedin. It is considered a good practice to extend interfaces in general or else create a new interface altogether.

In my view, the MetadataValidator defined above is generic enough to do any validation at a project level. The zip uploaded is at a project level, so the validation can only be done at a project level in Azkaban. We have to add a class Metadata and add generic types to it to be passed as a parameter to validateProject() method.

@HappyRay What do you think?
