### ISSUE TITLE
azzkaban api call for fetch running execution is not working

### ISSUE THREAD

**Issue by tk0485** [azkaban/azkaban#823]
trying to run :
curl -k -data "session.id=34ba08fd-5cfa-4b65-94c4-9117aee48dda&ajax=getRunning&project=azkaban-test-project&flow=test"' https://localhost:8443/executor

but its not working, its giving me error: couldn't resolve host 
is this endpoint has been depreciated? I checked it in azkaban source code and it seems to be there but for some reason its not working. is it a bug? or am I doing something wrong?

**Comment by fsi206914** [comment]
@tk0485 are testing Azkaban using your solo server? the default port should be 8081, right?

**Comment by tk0485** [comment]
yes, I'm using a solo server and the port is configured. Other api calls work fine and I can get the session id fine too except for this call.

**Comment by KyleFung** [comment]
Maybe it's a copy paste error into github, but it seems your quotes don't match. Can you confirm this?
Just before your host name you have a double quote followed by a single quote.

**Comment by tk0485** [comment]
@KyleFung as you have already guessed .. its a copy paste from azkaban github page, I deleted the single quote when I used the curl command in my tests.

**Comment by tk0485** [comment]
I found the reason for my issue. There is a missing dash from the --data in the curl command, the curl command should like:
curl -k --data "session.id=34ba08fd-5cfa-4b65-94c4-9117aee48dda&ajax=getRunning&project=azkaban-test-project&flow=test" https://localhost:8443/executor

instead of having a single dash leading "data", I also deleted the extra single quote before hostname. Could Azkaban team please update their documentation to reflect the correct command.

**Comment by KyleFung** [comment]
Fixed. Thanks for reporting.

**Comment by KyleFung** [comment]
Closed via #826
