### ISSUE TITLE
Error Installing Azkaban

### ISSUE THREAD

**Issue by rajivchodisetti** [azkaban/azkaban#838]
HI ,

I have installed Azkaban webserver and exec server today and when I ran the job , I am running into below exception and am not using any plugins so not sure where to set azkaban.native.lib to false 

Can you please help me in fixing this 

I was also trying to setup azkaban and ran into similar error , am not using solo server mode , I have installed both web and execution server separately

29-11-2016 17:02:49 IST dim_date INFO - Starting job dim_date at 1480419169234
29-11-2016 17:02:49 IST dim_date INFO - azkaban.webserver.url property was not set
29-11-2016 17:02:49 IST dim_date INFO - job JVM args: -Dazkaban.flowid=dim_date_redshift -Dazkaban.execid=692992 -Dazkaban.jobid=dim_date
29-11-2016 17:02:49 IST dim_date INFO - Building command job executor.
29-11-2016 17:02:49 IST dim_date INFO - 1 commands to execute.
29-11-2016 17:02:49 IST dim_date INFO - effective user is: azkaban
29-11-2016 17:02:49 IST dim_date ERROR - Job run failed!
azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
at azkaban.utils.Props.getString(Props.java:478)
at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:120)
at azkaban.execapp.JobRunner.runJob(JobRunner.java:685)
at azkaban.execapp.JobRunner.run(JobRunner.java:537)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
29-11-2016 17:02:49 IST dim_date ERROR - Missing required property 'azkaban.native.lib' cause: null
29-11-2016 17:02:49 IST dim_date INFO - Finishing job dim_date attempt: 0 at 1480419169261 with status FAILED

**Comment by kunkun-tang** [comment]
Please pull the latest code. This issue should already resolved by #827.

See  #818

**Comment by rajivchodisetti** [comment]
I have checked 818 and that is related to solo server mode but anyhow have pulled the latest code and tried yesterday but still the error is same

**Comment by kunkun-tang** [comment]
I see. You are running on standard mode, right?

**Comment by rajivchodisetti** [comment]
Yes , I have installed both web and executor server separately

**Comment by rajivchodisetti** [comment]
Is any one looking into it , am blocked on it :(

**Comment by kunkun-tang** [comment]
The easiest work around I can think of is to set execute.as.user to false in your common property file under plugin/jobtype.

https://github.com/jamiesjc/azkaban/blob/a3390cd154c26e9ef6734eb06b66ea72126b3eeb/azkaban-solo-server/build.gradle#L26

**Comment by rajivchodisetti** [comment]
@kunkun-tang when I built the project using gradle from source , there isn't any plugin/jobtype directory created .

And the link that you were referring to  refers to solo server mode where as I have installed webserver and exec server separately

**Comment by kunkun-tang** [comment]
Just create plugin/jobtype folder and put it inside executor folder.

**Comment by rajivchodisetti** [comment]
thanks for the revert , will try and get back

**Comment by cquptEthan** [comment]
@kunkun-tang   plugins/jobtypes folder

**Comment by kunkun-tang** [comment]
@cquptEthan Thanks for point out

**Comment by wenxzhen** [comment]
I set up the Azkaban on a machine with multiple executors on, but I still failed on azkaban 3.13.0

Any hints?
