### ISSUE TITLE
Azkaban shouldn't catch Throwables

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#844]
There are some occasions on Azkaban code where a `java.lang.Throwable` is caught.

These catch clauses should be changed to catch `java.lang.Exception`.

Do you agree?

----

On catching Throwable/Error/OutOfMemoryError:
http://stackoverflow.com/questions/2679330/catching-java-lang-outofmemoryerror
http://stackoverflow.com/questions/6083248/is-it-a-bad-practice-to-catch-throwable
http://stackoverflow.com/questions/352780/when-to-catch-java-lang-error

**Comment by kunkun-tang** [comment]
Went through all listed threads. Learned new things!

I checked quite a few throwable occurrences and found there are indeed many wrong usages.

**Comment by juhoautio** [comment]
I replaced all catches Throwable ->Exception and been running jobs fine so far. Also deployed some new job type plugins and did the reload. I could make a pull request about that?

**Comment by kunkun-tang** [comment]
Good to me.  @HappyRay , any thought?

**Comment by juhoautio** [comment]
I learned a bit more about the OOM issue. Exiting the thread that sees OOM is not enough to take down the java process, because typically there are still other (non-daemon) threads running, that keep the JVM up.

What I most likely need is the JVM option `-XX:+ExitOnOutOfMemoryError` (and a new enough JVM: http://www.oracle.com/technetwork/java/javase/8u92-relnotes-2949471.html).

It may be that Throwable-catching in Azkaban code doesn't cause any real problems.

**Comment by juhoautio** [comment]
I rather take back this suggestion, because it seems that catching Throwables could make things worse. Maybe sometimes a non-fatal throwable is thrown, and if it isn't caught, things like finishing a flow could be missed.
