### ISSUE TITLE
Azkaban should allow command execution for job notification

### ISSUE THREAD

**Issue by adfel70** [azkaban/azkaban#864]
It would really help us to connect Azkaban to out monitoring system. This could be done easily if Azkaban will expose another notification mechanism (in addition to the existing email notification) that will allow command execution. The command should get as an arguments the project name, flow name, execution id and status (success or fail).

We currently use [Sensu](https://sensuapp.org/), but I guess it should help others as it is the most general form of notification...

**Comment by kunkun-tang** [comment]
@adfel70 Have you tried this feature in AZ ? https://github.com/azkaban/azkaban/issues/442

**Comment by adfel70** [comment]
Yes, that definitely helps. Thanks :)
