### ISSUE TITLE
Where should I set the "azkaban.native.lib"

### ISSUE THREAD

**Issue by wenxzhen** [azkaban/azkaban#880]
I have tried several places to populate the "azkaban.native.lib" on Azkaban 3.13.0, but the Job never run up successfully.

Please help to advice.

> azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
> 	at azkaban.utils.Props.getString(Props.java:478)
> 	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:120)
> 	at azkaban.execapp.JobRunner.runJob(JobRunner.java:693)
> 	at azkaban.execapp.JobRunner.run(JobRunner.java:545)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 19-01-2017 18:10:54 CST SparkPi ERROR - Missing required property 'azkaban.native.lib' cause: null

Kind Regards,

**Comment by wenxzhen** [comment]
I found the path: azkaban_executor/plugins/jobtypes

**Comment by kunkun-tang** [comment]
How would you launch the solo server process, through Intellij/Eclipse? 

You would better run 
`ligradle installDist`
under azkaban-solo-server folder.

Then run it from azkaban-solo-server/build/install/azkaban-solo-server
