### ISSUE TITLE
Create configuration for azkaban-web-server and azkaban-exec-server

### ISSUE THREAD

**Issue by wyukawa** [azkaban/azkaban#914]
Hi

conf directory is not created when I build azkaban-web-server and azkaban-exec-server.

When I build azkaban-solo-server, conf directory is created.
But I encountered the problem which data in H2DB was broken, so I want to use azkaban-web-server and azkaban-exec-server.

Currently, there are following problems.

https://github.com/azkaban/azkaban/pull/827
https://github.com/azkaban/azkaban/issues/860

Of course, I can resolve this problems manually.

But if build.gradle is improved to resolve these problems, it would be nice.

Thanks

**Comment by kunkun-tang** [comment]
Not very sure if web server and executor could use the same H2 DB file. do you know? @wyukawa

**Comment by wyukawa** [comment]
Sorry, I'm not sure.

If I understand correctly,  web server and executor use the same MySQL DB.
Is that right?
I don't talk about azkaban solo mode, H2DB.

My request is to simplify to deploy azkaban(two server mode).

Thanks.

**Comment by kunkun-tang** [comment]
@wyukawa I usually create a separate folder to put my conf files(mysql information), and specify the folder path as argument when web server process starts. In this case, this change should not help much. I don't know how many people could get benefit by your idea.

**Comment by wyukawa** [comment]
Now, I do the following steps to deploy Azkaban after I build source codes and setup mysql.

```
mkdir azkaban-web-server-${version}/conf
vim azkaban-web-server-${version}/conf/azkaban.properties
vim azkaban-web-server-${version}/conf/azkaban-users.xml
vim azkaban-web-server-${version}/conf/log4j.properties
azkaban-web-server-${version}/bin/azkaban-web-start.sh
```

```
mkdir azkaban-exec-server-${version}/conf
vim azkaban-web-server-${version}/conf/azkaban.properties
vim azkaban-web-server-${version}/conf/log4j.properties
mkdir azkaban-exec-server-${version}/plugins/jobtypes/
vim azkaban-exec-server-${version}/plugins/jobtypes/commonprivate.properties
azkaban-exec-server-${version}/bin/azkaban-executor-start.sh
```

If this steps are simplified, it would be nice.

**Comment by sunghyuk** [comment]
May I submit a PR for this?  
I want to just edit properties files after building the package.

**Comment by HappyRay** [comment]
@sunghyuk  Thanks.

These packages are designed for production use. I think it makes more sense for the configs to be managed separated, possibly in a separate Git repo. 

The solo server is designed for non production use. @juhoautio is doing some work there to improve the experience. See #1423
