### ISSUE TITLE
azkaban crontab fail to execute when the task is timeout.

### ISSUE THREAD

**Issue by duanyixuan** [azkaban/azkaban#946]
hi,azkaban group:
 recently,i discover some problems about azkaban crontab. for example, sometimes,some job flow execution over one hour in some time, but that is crontabed every hour. As a result, it can`t be executed next hour. it can be normaly executed  thrid hour.
 in old version, there is no problem about this.
 finally, the suggestion is that azkaban start and shutdown scripts add the following code.

bin=`cd $(dirname $0);pwd`
azkaban_dir=$bin/..
cd ${azkaban_dir}

**Comment by hreview** [comment]
make sure your concurrent run option is turned off:
http://azkaban.github.io/azkaban/docs/latest/
 and search for "Concurrent Options"

**Comment by kunkun-tang** [comment]
@duanyixuan I don't understand your question. You want executions every hour even though one execution lasts more than 1 hours?

**Comment by duanyixuan** [comment]
@kunkun-tang:
 you are right.  maybe i know how to do it.
first, choose Run Concurrently   under Concurrent Execution Options,
second,choose to do schedule setting.
crontab will follow Run Concurrently action

i think , it is a better way to display current "Concurrent Execution Options" setting on every flow under the schedule.
