### ISSUE TITLE
azkaban-solo startup issues

### ISSUE THREAD

**Issue by li-afaris** [azkaban/azkaban#957]
The startup script for azkaban-solo fails due to the 'set -o nounset ' flag in util.sh and unset variables in the start script.

`
$ ./gradlew build installDist
... build output truncated...

BUILD SUCCESSFUL

Total time: 51.111 secs
$ cd azkaban-solo-server/build/install/azkaban-solo-server; bin/azkaban-solo-start.sh
bin/azkaban-solo-start.sh: line 18: HADOOP_HOME: unbound variable
`

Will submit a patch shortly.

**Comment by ameyamk** [comment]
+1 for fixing solo server. We need this to work perfectly!

**Comment by kunkun-tang** [comment]
I guess this issue could be closed, as PR was merged.
