### ISSUE TITLE
tag  on flow and executor

### ISSUE THREAD

**Issue by sharks222** [azkaban/azkaban#968]
Currently, Azkaban supports the allocation of flow to the specified Executor to perform. However, we have encountered a situation, and set the label to the Executor and flow. When the Executor's tag and flow's tag are the same, flow will be assigned to the Executor. If Azkaban supports this feature, it will help Azkaban's rolling upgrade。Is Azkaban now having a plan to support this feature?

**Comment by ameyamk** [comment]
Yes this feature in development right now

**Comment by HappyRay** [comment]
Could you describe how you plan to use this feature to support rolling upgrade?

**Comment by zhuxt2015** [comment]
Assume I have thirty Executors , then create two tag A and B, the A have 15 Executors，and B have another 15 Executor,when upgrade Executors of A，all flows set to B. vice versa.

**Comment by sharks222** [comment]
If I have developed a new function for Executor, I need to test this feature in a production environment. Add a tag A to the Executors with new feature and  then assign the flow to the  this group of Executors with tag A. If flow can run stably, then use the Executors directly, otherwise return to the previous Executors.

**Comment by sharks222** [comment]
@ameyamk How long  will this feature take?

**Comment by ameyamk** [comment]
Planned for Q2 - @chengren311 and mukund-thakur (https://github.com/mukund-thakur) have more details

**Comment by sharks222** [comment]
@chengren311 
hi,
How do you will  implement the Azkaban tag function?
Add the tag field to the executor and add the tag option to the job configuration.
Then match the tag before selecting Executor.
Right?

**Comment by chengren311** [comment]
@sharks222 it's flow-level option, which can be specified as execution option. More details can be found in this commit which is still under development: https://github.com/chengren311/azkaban/commit/8555143efc9c9faf06d33cf739997b4e6c34388a
