### ISSUE TITLE
MomentJS timezone broken

### ISSUE THREAD

**Issue by dmeijboom** [azkaban/azkaban#975]
I'm getting the following Javascript error in my console when trying to schedule a workflow:

![screenshot from 2017-04-09 16 21 28](https://cloud.githubusercontent.com/assets/3341876/24838044/a074a2ac-1d40-11e7-9b86-cfb52c9ccb3b.jpeg)

I think it has something to do with the fact that momentjs renamed it's timezone package from "moment-timezone-with-data-2010-2020.min.js" to "moment-timezone-with-data-2012-2022.js" while in Gradle it's still: https://github.com/azkaban/azkaban/blob/8de25c09d177234022dcd22ae1d502d59085709b/azkaban-web-server/build.gradle#L96

I'm not sure though because I don't have any experience with Gradle. Note that as of right now I'm not able to schedule workflows at all because of this bug.

**Comment by ameyamk** [comment]
We are not able to reproduce the bug - but to get you unblocked you can try and schedule flows via API

**Comment by kunkun-tang** [comment]
@dmeijboom You are likely right. I just rebuild the code, found that moment-timezone-with-data-2012-2022.js replaced the original file name. I will do a PR to fix this problem. For now, please use @ameyamk 's suggestion to send schedules. Thanks.

**Comment by dmeijboom** [comment]
Thanks!
For now I've fixed it by manually downloading momentjs to the old filename.

**Comment by kunkun-tang** [comment]
#979 fixed.
