### ISSUE TITLE
Azkaban can't schedule job at second-precision

### ISSUE THREAD

**Issue by Codefor** [azkaban/azkaban#981]
I schedule a job at mid night, that is, 2017-04-11 00:00:00 for example.
However, Azkaban schedule the job at 00:00:17.

**Comment by kunkun-tang** [comment]
How could you make a schedule as 00:00:00? Azkaban can only do 00:00. Second granularity is not supported for now.

**Comment by ameyamk** [comment]
Scheduled time and actual run time bay differ by few seconds if server is loaded/ DB is slow etc. That might explain why actual run time of the job may be different than scheduled time
